### ISSUE TITLE
new emojis do not show good on textview 

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#1001]
i would like to reopen this issue 
https://github.com/vanniktech/Emoji/issues/788

i downloaded the last code of github and i tested the example and i continue having the same problem :(
also if i use the library on my app
implementation "com.vanniktech:emoji-ios:0.18.0-SNAPSHOT"
i have the same result

![Screenshot_20230628-015536_Emoji](https://github.com/vanniktech/Emoji/assets/3120114/99029730-dad1-4441-a046-b1b5fe2d97c2)

**Comment by vanniktech** [comment]
Can you post the emoji strings here, so I can copy them?

**Comment by hvar90** [comment]
these are the emojis 
😮‍💨🤥🫨😌🫠😶‍🌫️🫥😶

**Comment by vanniktech** [comment]
Can't reproduce. Feel free to send a PR with a fix:

![android_screenshot_1688675655](https://github.com/vanniktech/Emoji/assets/5759366/985bdee0-1021-4ef2-acd0-b82a21f83dbe)

**Comment by hvar90** [comment]
@vanniktech you tested on EditTextview, on EditTextview it works good, the problem is only on TextViews, try to test there maybe  you get the same result as me

**Comment by vanniktech** [comment]
Also works:

![android_screenshot_1688679667](https://github.com/vanniktech/Emoji/assets/5759366/1fd0feaf-b672-4be3-ada2-7b4eee0541b5)

**Comment by hvar90** [comment]
i could find a way to reproduce the problem 
the problem happens on EditTextViews too
on file MainActivity.kt
change the setOnClickListener to recreate the activity
put these emojis on the EditTextView 
🫤🥹😶‍🌫️🫥🫠
then click on send button
after recreating the activity the emojis will change 
tell me if you can recreate the problem
i think solving that problem is possible solving the problem for TextView too
```
 binding.chatSend.setOnClickListener {
     /* val text = binding.chatEditText.text.toString().trim { it <= ' ' }
      if (text.isNotEmpty()) {
        chatAdapter.add(text)
        binding.chatEditText.setText("")
      }*/
      recreate()
    }
```
### emojis before recreating acivity
![Screenshot_20230707-105504_Emoji](https://github.com/vanniktech/Emoji/assets/3120114/6717de89-83e7-48fd-b081-6b2608c62be8)
### emojis after recreating acivity
![Screenshot_20230707-105517_Emoji](https://github.com/vanniktech/Emoji/assets/3120114/4fdcc401-b041-46f1-a606-ca1aeab5b4c6)

**Comment by vanniktech** [comment]
Nope. Still can't. But hey since you can, please submit a PR with a fix :)
