### ISSUE TITLE
Switch GoogleCompat to emoji2

### ISSUE THREAD

**Issue by singpolyma** [vanniktech/Emoji#1007]
Currently it's using the old androidx.emoji package, which is deprecated.

**Comment by vanniktech** [comment]
Feel free to PR.

**Comment by adbenitez** [comment]
IIRC emoji2 requires minimum android version to be 5+
I hope this library doesn't drop support for android 4, but I am just looking into it, I am still not sure what is the minimum SDK supported

**Comment by vanniktech** [comment]
We have minSdk 21 so we don't support Android 4
