### ISSUE TITLE
popupWindowHeight does not seem to have any effect on the displayed hight

### ISSUE THREAD

**Issue by singpolyma** [vanniktech/Emoji#1008]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: com.vanniktech:emoji-google:0.18.0-SNAPSHOT
- Affected devices: emulator

Using `SearchInPlaceTrait` and the popup window is quite large (most of the vertical space) would prefer it be smaller, but settings `popupWindowHeight` on the `EmojiPopup` I pass to the trait does not seem to have any effect.

**Comment by vanniktech** [comment]
I think the `popupWindowHeight` is only meant to be for the actual `EmojiPopup`. Are you currently setting that one and want it to be respected or do you want another customization point (in which case we should add it to the SearchInPlaceTrait constructor).

**Comment by singpolyma** [comment]
I'm not clear on how the "actual `EmojiPopup`" differs from the one being shown by the `SearchInPlaceTrait` but either way I'm just looking for a way to limit the height so it doesn't cover most of the screen while searching

**Comment by vanniktech** [comment]
Can you share a screenshot of the `SearchInPlaceTrait` that you think that is too big?
