### ISSUE TITLE
Make EmojiManager categories and/or emojiProvider public

### ISSUE THREAD

**Issue by singpolyma** [vanniktech/Emoji#1009]
Needed to implement a tweaked `SearchEmoji`

**Comment by vanniktech** [comment]
More details, why?

**Comment by singpolyma** [comment]
If you look in the library's own implementation of `SearchEmoji` you'll find it is used there -- there needs to be some way to get at the list of emoji in order to search them.

**Comment by vanniktech** [comment]
Since you call `fun install(provider: EmojiProvider)` you can also use the thing you passed yourself.
