### ISSUE TITLE
Reflect Emoji Skin Tone automatically in Emoji List

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#101]
When changing the skin tone of an Emoji in a Category the Emoji Icon in the list should be updated. 

1. Look for 👊
2. Long press on 👊 
3. Change in Dialog to 👊🏻
4. In the list 👊🏻 should be displayed now instead of 👊

If we do this we should no longer then display 👊 & 👊🏻 in the recent Emojis. Instead just display the one that was used last.

**Comment by RicoChr** [comment]
I'd like to try this. For the persistence part of this, I would either introduce a new class "RecentSkintoneManager" or integrate the functionality into "RecentEmojiManager". What do you think?

I'm planning this, as I'm still becoming familliar with the code base and don't want to rush anything.

**Comment by vanniktech** [comment]
Probably a new class since RecentEmojiManager can be overridden with a custom implementation.

**Comment by vanniktech** [comment]
@RicoChr still interested in trying this out?

**Comment by RicoChr** [comment]
I'm on it. I don't have much time right now so if I can't make it today i'll pass.
