### ISSUE TITLE
SearchInPlaceTrait sometimes opens new popup

### ISSUE THREAD

**Issue by singpolyma** [vanniktech/Emoji#1010]
- Version of the library: com.vanniktech:emoji-google:0.18.0-SNAPSHOT
- Affected devices: emulator

For example if I type `:ta` then pause then type `da` I get the popup with the tada emoji by itself on top of a second popup with the results for `ta`.  Searching, then backspace all the way to the `:` then another search often triggers this issue as well.

**Comment by vanniktech** [comment]
Can't reproduce. Feel free to submit a PR with the fix.
