### ISSUE TITLE
import com.vanniktech.EmojiTextView not working

### ISSUE THREAD

**Issue by adbenitez** [vanniktech/Emoji#1024]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 1.17.0
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

I am following the README and adding:

```
implementation "com.vanniktech:emoji-ios:0.17.0"
```

to my build.gradle file, then I try to import:

``
import com.vanniktech.emoji.EmojiManager; // <- works
import com.vanniktech.emoji.google.GoogleEmojiProvider; // <- works
import com.vanniktech.EmojiTextView; // <- does NOT works: Cannot resolve symbol
```

the project I am trying to add this library is a java project, not Kotlin, could that be related? thanks in advance

**Comment by adbenitez** [comment]
@vanniktech could you at least say why the issue was closed? thanks in advance and sorry if I did something wrong

**Comment by vanniktech** [comment]
probably needs to be `import com.vanniktech.emoji.EmojiTextView`

**Comment by adbenitez** [comment]
@vanniktech ah sorry for that! it was that after `import com.vanniktech.emoji.EmojiTextView` failed I tried without the "emoji" subpackage because reading old issues it seems at some point it was like that, but the issue is that `import com.vanniktech.emoji.EmojiTextView` is not working, I updated the issue title and description

**Comment by adbenitez** [comment]
re-created with correct info: https://github.com/vanniktech/Emoji/issues/1025
