### ISSUE TITLE
import com.vanniktech.emoji.EmojiTextView not working

### ISSUE THREAD

**Issue by adbenitez** [vanniktech/Emoji#1025]
- Version of the library: 1.17.0
- Affected devices:
- Affected versions:

Screenshot showing the issue:
![image](https://github.com/vanniktech/Emoji/assets/24558636/c62a2232-23b5-49be-9bb7-79ad105a6031)

----------------------------------------------------------------------

I am following the README and adding:

```
implementation "com.vanniktech:emoji-ios:0.17.0"
```

to my build.gradle file, then I try to import:

```
import com.vanniktech.emoji.EmojiManager; // <- works
import com.vanniktech.emoji.google.GoogleEmojiProvider; // <- works
import com.vanniktech.emoji.EmojiTextView; // <- does NOT works: Cannot resolve symbol
```

also using in layout xml files doesn't work

the project I am trying to add this library is a java project, not Kotlin, could that be related? thanks in advance

**Comment by vanniktech** [comment]
This works fine in the sample app, please consult with it. I don't have time to do individual support

**Comment by adbenitez** [comment]
thanks! in fact after looking at the example app's build.gradle it turns out I need to add the kotlin plugin to my project (which doesn't use kotlin) that fixed it! sadly just to realize the library requires min SDK 21 while my project targets min SDK 16 :broken_heart:

**Comment by vanniktech** [comment]
SDK 21 is the way to go

**Comment by alexeygritsenko** [comment]
I have the same problem in java project. My minSdk is 24, targetSdk is 34.
@adbenitez, could you provide examples code of what and where you wrote in build.gradle file or somewhere else?
