### ISSUE TITLE
EmojiPopup not dismissing, when back press.

### ISSUE THREAD

**Issue by pankaj89** [vanniktech/Emoji#103]
Hello, when EmojiPopup is visible and I press back button on device, then Softkeyboard is dismissed, but Emoji Popup is not dismissed.

- Version of the library:'com.vanniktech:emoji-ios:0.4.0'
- Affected devices: Samsung, Emulator(Nexus 6)

**Comment by vanniktech** [comment]
Can you try out `0.5.0-SNAPSHOT` ?

**Comment by pankaj89** [comment]
I am using 
compile 'com.vanniktech:emoji-ios:0.5.0-SNAPSHOT'

Failed to resolve 'com.vanniktech:emoji-ios:0.5.0-SNAPSHOT'
Is this is in maven repository or jcenter?

**Comment by vanniktech** [comment]
You need to add the snapshot url for maven.

**Comment by pankaj89** [comment]
Hi, Its working fine in 0.5.0-SNAPSHOT.
One more thing, There is space between EmojiGridView cells, so when we click in between two emoji it does nothing, you can increase the padding in cell and remove spacing between cells.
Thanks

**Comment by vanniktech** [comment]
Sounds good. Then for now try to stick with `0.5.0-SNAPSHOT`. I'll release it soon as `0.5.0`
