### ISSUE TITLE
Indents suggestions

### ISSUE THREAD

**Issue by huskcasaca** [vanniktech/Emoji#1034]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------
I think that using an indent size of `4` is more appropriate for a Kotlin project. It also aligns with the official style guide.

**Comment by vanniktech** [comment]
I like 2 and use square code styles.
