### ISSUE TITLE
IosEmojiProvider not available by using compile 'com.vanniktech:emoji-ios:0.4.0' only

### ISSUE THREAD

**Issue by gatanga** [vanniktech/Emoji#104]
Hi Niklas,

First off, thank you for a great lib. I have used it in a library before and I am using it again for my current project. It is great.

Second, using 'compile 'com.vanniktech:emoji-ios:0.4.0'' results in IosEmojiProvider class not found. Basically, the whole ios package is not available. For now I imported the project as a module but would be helpful if you could please have a look into it.

Thanks,
Jean Marie

Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.4.0
- Affected devices: All
- Affected versions: All

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Hmm that is weird. I can [find it on mavenCentral](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22emoji-ios%22)

`compile 'com.vanniktech:emoji-ios:0.4.0'` should to the trick. You can also do the following `./gradlew assembleDebug --refresh-dependencies` to reload the dependencies.

**Comment by hellsayenci** [comment]
Hi,

Really great library. 0.3.0 version were working fine. But the 0.4.0 version missing external library folders. When I look the external libraries in my project there is no "emoji-ios", "emoji-android" and "emoji-one" folders. I also refreshed dependencies.

![screen shot 2017-03-17 at 11 33 22](https://cloud.githubusercontent.com/assets/11094251/24035244/649c9514-0afd-11e7-8fd4-e043cda9da9c.png)

**Comment by vanniktech** [comment]
@hellsayenci It seems like you're using `compile 'com.vanniktech:emoji:0.4.0'` and you should be using `compile 'com.vanniktech:emoji-ios:0.4.0'` instead

**Comment by vanniktech** [comment]
@hellsayenci did it work?

**Comment by hellsayenci** [comment]
@vanniktech oh yes, It was my bad. Library working like a charm. Thanks for ur help 👍
