### ISSUE TITLE
Add possibility to create own textviews with emoji

### ISSUE THREAD

**Issue by RomanTruba** [vanniktech/Emoji#105]
Now we can only subclass `EmojiTextView` to create emoji text views, because `EmojiHandler` class is package-only. However, this is not possible to pass custom emoji size, except using attributes.
Please, make `EmojiHandler` class public or provide function to override for `EmojiTextView` to provide default value for emojiSize.

**Comment by vanniktech** [comment]
Why don't you subclass `EmojiTextView` ?

**Comment by RomanTruba** [comment]
Hi, sorry, I just missed `setEmojiSize()` method yesterday. 
Actually, I can do now what I want.
