### ISSUE TITLE
Emoji pop-up keyboard sometime display no-emoji

### ISSUE THREAD

**Issue by Hemant-Ayoba** [vanniktech/Emoji#1062]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.17.0(com.vanniktech:emoji-ios)
- Affected devices: All
- Affected versions: All

Screenshot(s) showing the issue and reproduction steps are appreciated.

----------------------------------------------------------------------

<img width="372" alt="Screenshot 2024-03-05 at 11 28 45 AM" src="https://github.com/vanniktech/Emoji/assets/136078031/baf0e849-c534-489f-866d-7d190a362e42">

**Comment by vanniktech** [comment]
Can you reproduce with the sample app?
