### ISSUE TITLE
If I am using compile 'com.vanniktech:emoji-ios:0.4.0', how can I change to use the emoji with skin tone changing function? Thank you

### ISSUE THREAD

**Issue by clementf2b** [vanniktech/Emoji#107]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Will be in `0.5.0` which is not yet released so you can use `0.5.0-SNAPSHOT`.

**Comment by clementf2b** [comment]
//emoji
    compile 'com.vanniktech:emoji-one:0.5.0-SNAPSHOT'

It returns this for me
![screen shot 2017-04-03 at 9 45 44 pm](https://cloud.githubusercontent.com/assets/9070390/24612127/ed5715de-18b6-11e7-8b7e-b48127970b53.png)

**Comment by vanniktech** [comment]
You need to add the maven snapshot url.

**Comment by clementf2b** [comment]
I get what you mean. Thanks

**Comment by searchy2** [comment]
What is the snapshot URL? I would like to try the latest prerelease too.

**Comment by vanniktech** [comment]
`https://oss.sonatype.org/content/repositories/snapshots`

**Comment by searchy2** [comment]
> maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
