### ISSUE TITLE
Request: add an API for filtering out unwanted emojis by name string

### ISSUE THREAD

**Issue by adi-vizgan-unplugged** [vanniktech/Emoji#1074]
Request: add an API for filtering out unwanted emojis by name string.
The feature should have some kind on an API that allows you to input strings to it, and any emojis that contains these strings will not be populated to the emoji view.

**Comment by vanniktech** [comment]
Just roll your own Emoji Provider where you aren't providing them.

**Comment by adi-vizgan-unplugged** [comment]
@vanniktech Didn't think of that, thanks! I copied the Google emoji provider which is the one I use and removed the unwanted emojis from it, and passed it to the install method and it works!

**Comment by vanniktech** [comment]
You could also write your own Emoji Provider and inside instantiate the one from Google and filter out the emojis you don't want. That way you don't have to copy all the code and can filter just like you want to.
