### ISSUE TITLE
Support new emoji in iOS 17.4

### ISSUE THREAD

**Issue by tiennv157** [vanniktech/Emoji#1079]
![GL_y_OvasAAr9wH](https://github.com/vanniktech/Emoji/assets/49298106/8e322987-9958-4fe2-a067-53215f231551)

It is showing like that at version 0.18.0

<img width="308" alt="Screenshot 2024-04-26 at 11 08 04" src="https://github.com/vanniktech/Emoji/assets/49298106/0b9657c6-cab7-42bc-8447-f5f94114f425">

**Comment by vanniktech** [comment]
Can you check with https://github.com/vanniktech/Emoji/pull/1085 please?

**Comment by vanniktech** [comment]
Please reopen. If this still exists. And if so, we need to file an issue at our JavaScript data source to include them.

**Comment by tiennv157** [comment]
Thank you for your work. I see it in your new commit. Waiting for new release
