### ISSUE TITLE
IosEmojiProvider is missing in 'com.vanniktech:emoji:0.5.0-SNAPSHOT' Version

### ISSUE THREAD

**Issue by pankaj89** [vanniktech/Emoji#109]
IosEmojiProvider is missing in 
compile 'com.vanniktech:emoji:0.5.0-SNAPSHOT'

So how to initialize in Application class just like in previous we use
EmojiManager.install(new IosEmojiProvider());

In SNAPSHOT Version?

**Comment by vanniktech** [comment]
You need to use the right one. It's suffixed with -ios

Have a closer look at the Readme.
