### ISSUE TITLE
Add missing Symbols

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#11]
A lot are missing and so far I haven't figured out which ones exactly.

**Comment by EmmanuelMess** [comment]
[Full list (unicode.org)](http://unicode.org/emoji/charts/full-emoji-list.html), there are 1624...

**Comment by vanniktech** [comment]
@EmmanuelMess yeah but not all of those are Symbols ;)

**Comment by EmmanuelMess** [comment]
@vanniktech What would "Symbols" be?

**Comment by vanniktech** [comment]
Emojis in the last category. (The one with the !?#`) If you compare the emojis in this library to the ones that Whatsapp supports there are a few missing.

**Comment by EmmanuelMess** [comment]
27 are missing. [Here](http://emojipedia.org/symbols/)'s the list of Symbols. Will try to order the numbers in Symbol class.

**Comment by vanniktech** [comment]
Hmm I ordered them in the way Whatsapp displays them but I did not find a table for that only yet. The one you pointed out differs from the ordering in Whatsapp :/

**Comment by vanniktech** [comment]
Implemented by #77
