### ISSUE TITLE
EmojiOneProvider is missing in 'com.vanniktech:emoji-one:0.4.0'

### ISSUE THREAD

**Issue by luichanfe** [vanniktech/Emoji#115]
The import 'import com.vanniktech.emoji.one.EmojiOneProvider;' doesn't exist. And gradle doesn't find 'com.vanniktech:emoji-one:0.4.0-SNAPSHOT' or 'com.vanniktech:emoji-one:0.5.0', neither 'com.vanniktech:emoji-one:0.5.0-SNAPSHOT'

**Comment by vanniktech** [comment]
`0.5.0` isn't released yet. and for `0.5.0-SNAPSHOT` you'll need to add the maven snapshot url to your repositories. `0.4.0-SNAPSHOT` was deleted once `0.4.0` was released. So for now just use `0.4.0`

**Comment by luichanfe** [comment]
Ok, thanks. But the problem I'm having is that **com.vanniktech.emoji.one.EmojiOneProvider** doesn't come with **com.vanniktech:emoji-one:0.4.0**

**Comment by vanniktech** [comment]
I just tried it about and I can find it `com.vanniktech.emoji.one.EmojiOneProvider`. Maybe do a clean build?

**Comment by luichanfe** [comment]
Thanks, trying several times syncing gradle and worked. Thanks for your time
