### ISSUE TITLE
Line height issues

### ISSUE THREAD

**Issue by justmobilize** [vanniktech/Emoji#116]
Hey, first thanks so much for this. Was able to delete a bunch of code and not need to keep up on it thanks to you.

One issue I have seen is around line height. Looking at the two images:

![image](https://cloud.githubusercontent.com/assets/1547881/25717049/24bdd1a4-30b6-11e7-8369-ceed90d52987.png)

![image](https://cloud.githubusercontent.com/assets/1547881/25717066/2e56b5b4-30b6-11e7-8a5e-4183ade88313.png)

You'll notice that when the lines wrap, the line height on the second line when there is no text is different. Any thoughts of why? I noticed in ours (had a similar problem) that without text the edit text reported a different size.

On another note, like emoji size, would love to have an optional emoji padding to help space out emojis.

**Comment by vanniktech** [comment]
No idea to be honest. Also never noticed it.

**Comment by justmobilize** [comment]
This is great, if you don't modify the line height. But if you adjust `lineSpacingExtra` you get:

20sp
![image](https://cloud.githubusercontent.com/assets/1547881/25815603/02b765f2-33d6-11e7-9aff-cf3f47fae93e.png)

50sp
![image](https://cloud.githubusercontent.com/assets/1547881/25815620/1bd3b1c6-33d6-11e7-8abe-36ee5404bcbf.png)
