### ISSUE TITLE
Center Emoji in line

### ISSUE THREAD

**Issue by Sese-Schneider** [vanniktech/Emoji#121]
Hi,

is it somehow possible to **center** an emoji in its line?

![7aee1719-fb3c-4110-b3ad-a08986765244](https://cloud.githubusercontent.com/assets/14337484/26037543/52d7eb96-38f5-11e7-8916-c28fc6f4878d.png)

I manually set the lineheight via `emojiTextView.setLineSpacing(0f, 1.5f);`
Unfortunately the emoji "drops" and is not displayed centered.

I could not find any method in your files to do this.
If there is none could you add this in a future release please?

With kind regards, 

Sebastian Schneider

**Comment by vanniktech** [comment]
I don't think you'll need to do anything in order to let it be centered. Maybe the line spacing is causing this dropping down effect.

**Comment by Sese-Schneider** [comment]
How can i fix this then?
I just set the emoji size, text size and linespacing according to doc. emoji is unicode added

**Comment by vanniktech** [comment]
Can you try `0.5.0-SNAPSHOT` and see whether this changes anything. Note: setEmojiSize has been removed and instead `lineHeight` from TextView is used.

**Comment by justmobilize** [comment]
There are some other issues with the new line height settings. adding this:
```

**Comment by vanniktech** [comment]
Interesting. Maybe support for those attributes have to be added too.

**Comment by justmobilize** [comment]
Might I suggest you leave both options in there? So if size is undefined it used the line height otherwise the  emoji size?

I don't think line height will ever look right if changed, since it's all below the text. And I assume most people would want either centered or bottom aligned.

**Comment by vanniktech** [comment]
So using `emojiSize` if it's defined otherwise the line height?

**Comment by justmobilize** [comment]
I think that would be the best of both worlds.

**Comment by vanniktech** [comment]
@justmobilize would you like to submit a PR?

**Comment by Sese-Schneider** [comment]
@vanniktech how can i include this update into my gradle files?

**Comment by vanniktech** [comment]
Use the maven snapshot url and use `0.5.0-SNAPSHOT`.

**Comment by vanniktech** [comment]
Which approach are you using?

**Comment by shamoorti** [comment]
compile 'com.vanniktech:emoji-ios:0.5.0-SNAPSHOT' with a RecyclerView for messages. Look at this:
![photo_2017-06-26_15-27-42](https://user-images.githubusercontent.com/10776933/27541526-83eb8318-5a84-11e7-865e-ca3e10d08446.jpg)
If the text is combined with Emojies then there is no problem, but if you just send emojies and you re-open the app then the line height gets 0 and as the image shows.

**Comment by vanniktech** [comment]
Hmm what does your xml layout declaration / java code look like? Try out the sample and just send an Emoji. In there it does work.

**Comment by shamoorti** [comment]
Actually it works on Emulator with no problem! And if I change no non SNAPSHOT version then it would be fine but the emoji keyboard not closing on back press happens!

<com.vanniktech.emoji.EmojiTextView
            android:id="@+id/textMessage"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAlignment="textStart"
            android:layout_gravity="start"
            android:textStyle="normal"
            android:textColor="@color/chatTextMainColor"
            android:textSize="16sp" />

The code is exactly as your sample. I haven't add anything special.

**Comment by vanniktech** [comment]
Maybe the `textStyle` or `textAlignment` adding just emojis does work in the sample.

**Comment by shamoorti** [comment]
Let me check more. The weird thing is that it doesn't have any problem in the emulator.

**Comment by vanniktech** [comment]
Yup I do. I also yesterday briefly experimented with displaying the emoji in a bigger size when you only send one (similary to what Whatsapp & Slack does) and I also stumbled upon some problems. I definitely want this to get fixed before doing `0.5.0`.

**Comment by shamoorti** [comment]
That would be great if it's fixed soon. We plan to release and use your library in end of July so we would be really happy if it's fixed. But I will try to go around and test different cases to see if it's possible to fix it.

**Comment by vanniktech** [comment]
I'd fix it right away if the project I'm working on would require this library. Unfortunately priorities have changed recently and it's a complete side project.

I also created #148 for further discussion about the Emoji size potential.

**Comment by shamoorti** [comment]
Excellent, we really appreciate your great work. Good luck.

**Comment by justmobilize** [comment]
I can also look into some of this. We are a handful of commits back (before the sizing started to change) and resizing single emojis (without text works).

**Comment by vanniktech** [comment]
I'd appreciate any help. I'm also waiting with `0.5.0` until this sizing is resolved.
