### ISSUE TITLE
Back button hides pop up but it shows soft keyboard dismissing afterwards

### ISSUE THREAD

**Issue by jorgevalbuena56** [vanniktech/Emoji#124]
It is possible to dismiss the soft keyboard before dismissing the pop up? The way it is right now you can tell that the soft keyboard was behind even if I never showed it on the screen.

the version that I am using is the last one and the device is a Samsung galaxy note 5 with lollipop.

Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Can you try 0.5.0-SNAPSHOT?

**Comment by jorgevalbuena56** [comment]
Where is that snapshot, I can't find it in the gradle repo

I have this in my gradle file:
compile 'com.vanniktech:emoji-ios:0.5.0-SNAPSHOT'

**Comment by vanniktech** [comment]
You need to add the snapshot url as a maven repo: `https://oss.sonatype.org/content/repositories/snapshots`

**Comment by jorgevalbuena56** [comment]
No I getting this error:

Error:(78) No resource identifier found for attribute 'emojiSize'

**Comment by vanniktech** [comment]
Yes that one has been removed. Please use setLineHeight now.

**Comment by jorgevalbuena56** [comment]
I changed it and I still getting the same error:
                <com.vanniktech.emoji.EmojiEditText
                    android:id="@+id/chat_edit_text1"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:layout_marginStart="12dp"
                    android:layout_marginEnd="12dp"
                    android:hint="@string/type_your_message"
                    android:inputType="textMultiLine"
                    android:textSize="16sp"
                    android:textColorHint="@color/hint_type"
                    android:background="@null"
                    android:text="@{viewModel}"
                    android:onClick="@{viewModel.onMessageTypeClicked()}"
                    app:setLineHeight="26sp">
                        <requestFocus />
                    </com.vanniktech.emoji.EmojiEditText>

Error:(78) No resource identifier found for attribute 'setLineHeight'

**Comment by vanniktech** [comment]
Oh sorry. Use the `setLineHeight` method from TextView. Otherwise you can also have a look at the sample that changes the emoji size.

**Comment by jorgevalbuena56** [comment]
There's not setLineHeight method in TextView neither in the EditText, I think you meant setLineSpacing ??

**Comment by vanniktech** [comment]
[That's](https://github.com/vanniktech/Emoji/blob/0af3ed915b418a5a9d366e2b562454bf8bc1216d/app/src/main/res/layout/adapter_chat.xml#L13) how the sample changes the size.

**Comment by jorgevalbuena56** [comment]
So much of a hassle just to try a completely different thing...

**Comment by b3nnee** [comment]
You should use... 

`android:textAppearance = "@style/TextAppearance.AppCompat.Medium"`

**Comment by vanniktech** [comment]
@jorgevalbuena56 is this now resolved?

**Comment by jorgevalbuena56** [comment]
This is not resolved, I still can see the keyboard dismissing after the pop up. It will never work if u show the keyboard and then the pop up. I was able to do a workaround with the back button but still is not the desire effect.

**Comment by vanniktech** [comment]
Can you post a video or gif that shows the issue? And explain what you'd expect?

**Comment by jorgevalbuena56** [comment]
I only expect that if I tap the emoji button, never see a keyboard again, even if I hit the back button. Once the view switches to the emoji view pager, the Softkeyboard must be completely hidden, instead it's overlapped by the view pager

**Comment by vanniktech** [comment]
@jorgevalbuena56 just merged a PR that adds the emoji size functionality back to `0.5.0-SNAPSHOT` (it should be out within an hour). Please report back.

**Comment by vanniktech** [comment]
I'll close this. Also I created #148 to track the Emoji size issue.
