### ISSUE TITLE
EmojiHandler.addEmojis is horribly slow

### ISSUE THREAD

**Issue by Ereza** [vanniktech/Emoji#127]
Hi! First of all, thanks for this library! I am currently using version 0.5.0-SNAPSHOT (due to issue #103), I don't know if this only happens with this version.

I have seen that `EmojiTextView` and similar are slow when the text is several lines long (I am using a text of about 10000 characters as a test). This blocks the UI thread and is specially noticeable when scrolling a `RecyclerView`.

When running on an emulator (with API 23 to be precise), executing `setText` on an `EmojiTextView` takes about half a second. When doing that in a normal `TextView` the result is immediate (less than 0.001 seconds). I have tried to analyze the behavior of the library and the problematic method is `EmojiHandler.addEmojis`, that seems to parse the full string in a while loop.

I have changed the code in my case to use a regular expression, and the result is amazing: it now takes around 0.002 seconds to execute setText, and the behavior is the same.

Even if you don't take the regexp approach, that method should be checked for optimization.

I attach a Gist of my changed class: https://gist.github.com/Ereza/08282caa4fa444bcbe41aedcc1c820b2

**Comment by vanniktech** [comment]
Interesting approach. The regex consists of all the possible Emojis right?

I know that performance isn't the best, although we did some improvements.

**Comment by Ereza** [comment]
Yes, that's right. I generated it from the list of drawables in the library. Maybe it could be constructed at runtime, or use some other approach to be able to support emojis other than the ones provided in the library. I just tried this way and it seems to be good enough for my case, but this way you can't add additional emojis like the library allows you to do..

**Comment by vanniktech** [comment]
Yup. The regex could be generated though since we also generate the category files. Although the different modules (google, ios, emojione) both support different emojis and the handler is in a core module.

How many of those 10000 characters are emojis?

**Comment by rubengees** [comment]
This seems like a great idea. I don't think it would be a good idea to generate it at build time, since that would take the flexability from it. Instead we could traverse the `EmojiTree` at runtime *once* and build the regex from it.

@vanniktech If you would be interested in this approach i could work at it.

**Comment by vanniktech** [comment]
Sure go for it. And traversing the EmojiTree is even better since then also custom emojis would work.

**Comment by Ereza** [comment]
I made some tests in a simple `Activity` with one `TextView` and one `EmojiTextView`. Here is the Gist of `Activity` with the tested strings: https://gist.github.com/Ereza/cc4daa7911fbd24a985fc52e0465aac4

I am not sure if the test strings are really 10000 characters long since I don't know exactly how emojis are considered one or two characters (string.length() returns 10000). But anyway, here are the results:

Using the current algorithm (10 iterations over `setText`, time is the sum of all of them):

- setText TextView No emojis: 0.0000
- setText EmojiTextView No emojis: 4.7752
- setText EmojiTextView Some emojis: 4.5184
- setText EmojiTextView Emojis: 2.4510

Using the regex (10 iterations over `setText`, time is the sum of all of them):

- setText TextView No emojis: 0.0000
- setText EmojiTextView No emojis: 0.0194
- setText EmojiTextView Some emojis: 0.0269
- setText EmojiTextView Emojis: 1.5967

What I see here too is that the current algorithm works better when there are more emojis.
