### ISSUE TITLE
API to query Emoji information about a String

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#128]
It'd be cool if you could query information about a String, such as whether it consists of only one Emoji or whether the entire String consists of multiple Emojis. Another one would be if the String consists of a specific Emoji (such as the heart ❤️ ), so it could be animated.

One use case would be to display the Emoji in a bigger size if it's only one. And for the multiple ones they might get a bit bigger too.

**Comment by rubengees** [comment]
This will be possible to some intent with the change i am working on.

**Comment by vanniktech** [comment]
Yup. I think the Tree will need to be reversed. That way also custom Emojis / provided Emojis would work.

**Comment by vanniktech** [comment]
Closed by #145
