### ISSUE TITLE
Using Emoji lib in buttons and other custom views

### ISSUE THREAD

**Issue by alzozov** [vanniktech/Emoji#136]
Hi vanniktech!
How to use (or extend) lib to display Emoji in buttons ?

![image](https://user-images.githubusercontent.com/741393/26875690-c98306ce-4b8b-11e7-894e-cf9790d95e65.png)

**Comment by vanniktech** [comment]
DrawableLeft with the image file

**Comment by alzozov** [comment]
Well.. Buttons are generated grammatically.
Tried to use EmojiHandler.replaceWithImages but it is not accessible outside the lib

**Comment by vanniktech** [comment]
We could do an EmojiButton. (Just look at how the other classes are done).

**Comment by alzozov** [comment]
Yes we can. I just can't make connection to github to commit. 

[EmojiButton.txt](https://github.com/vanniktech/Emoji/files/1057854/EmojiButton.txt)

**Comment by vanniktech** [comment]
Alright, I'll do it later.
