### ISSUE TITLE
Emoticon size issue with snapshot version

### ISSUE THREAD

**Issue by shamoorti** [vanniktech/Emoji#138]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: emoji-ios:0.5.0-SNAPSHOT
- Affected devices: Android
- Affected versions: API 16 and up

Hey and thanks for all your great efforts making this Git, as the problem with keyboard popup not vanishing after back button was pushed (Version 0.4.0), I was forced to use emoji-ios:0.5.0-SNAPSHOT version, but now when I change the emoji size with text height (Using lineSpacingExtra or lineSpacingMultiplier ) emojicons are cut in top and button. Have you managed to figure out any solution for this since before  it was an issue too but not chased.

**Comment by vanniktech** [comment]
There's an issue about this. I'm on mobile.

**Comment by Ereza** [comment]
I was having an issue that maybe has something to do with this. I am using an EmojiTextView inside a RecyclerView. In some cases, when the EmojiTextView only contained emojis it was being shown with height 0. Also, when another view with a higher height was recycled, the new view didn't set its height as expected and just kept the old height.

All these issues disappeared when i commented out the `getSize` method in `EmojiSpan`, and now everything works as expected. Could this change I made break anything? If not, maybe it would be nice to investigate why that happens.

**Comment by shamoorti** [comment]
I recognized the issue with the RecuclerView and the 0 height still exist with the project. When I send only Emojies and I close the app and re-open it, the height of the EmojiTextView becomes 0 and shows nothing! It becomes like the line. I think your problem does not have to do anything with the getSize. The problem is your RecyclerView.

**Comment by shamoorti** [comment]
I found another interesting point, the 0 height seems no problem on the emulator, I found some comments about the cashing size. Try to add this line to your RecyclerView and see if the problem with the 0 height of textView goes away.

**Comment by Ereza** [comment]
@shamoorti I don't know what you're talking about. I'm not using `EditText` anywhere.

**Comment by shamoorti** [comment]
Sorry for miss leading code, I know this is not about editText, in stackflow example is editText with RecyclerView. In your case is EmojiTextView. But the main issue is kinda the same.

**Comment by vanniktech** [comment]
Can this be closed in favor of #121?

**Comment by shamoorti** [comment]
Yes definitely. Thanks.

**Comment by vanniktech** [comment]
New issue: #148
