### ISSUE TITLE
Emoji Keyboard not hiding softkeyboard

### ISSUE THREAD

**Issue by Ebraheemb** [vanniktech/Emoji#139]
please help
![image](https://user-images.githubusercontent.com/12219367/27131863-4311bbb4-5115-11e7-8560-59399a67b8f2.png)

**Comment by vanniktech** [comment]
Please use the `0.5.0-SNAPSHOT` version.

**Comment by Ebraheemb** [comment]
![image](https://user-images.githubusercontent.com/12219367/27177451-1c29f3b2-51cf-11e7-802f-14e5f74649e8.png)

**Comment by vanniktech** [comment]
Add the snapshot url.
