### ISSUE TITLE
Not working on SDK <= 21

### ISSUE THREAD

**Issue by 70nyIT** [vanniktech/Emoji#141]
First of all congrats, this library is super useful and well done!

Reading other issues raised, as well as looking at build.gradle file,  I saw that the min sdk is 15. The problem is that the emoji keyboard is not showing up on sdk <= 21. This happens also with the "app" example project included in your code: I simply downloaded the code (git copy) and launched it.

I have tested the "app", as well as my app where I have integrated your library, in both Virtual and Physical device with the following SDK versions:
+ 16: not working 
+ 19: not working
+ 21: not working
+ 22: working
+ 23: working

Your "app" is using the version 0.5.0-SNAPSHOT, instead, the one I have imported into my app is using 0.4.0. Both are giving the same issue. The issue is present even if I switch from emoji-one to ios.

**Comment by vanniktech** [comment]
Hmm this seems strange. You should use the `0.5.0-SNAPSHOT` version.

Can you post a screenshot?

**Comment by 70nyIT** [comment]
Hi!
I have made those screenshots with the `0.5.0-SNAPSHOT` version, running the default app present inside your code, without editing a single line of code. There are no errors fired, even debugging it, but this is what I see.

This is the screenshot while I try to click on the emoticon button, on an emulator with API Level 21. As you can see, nothing happens.
![screenshot_api_21](https://user-images.githubusercontent.com/12898752/27430721-edf4a3ae-5749-11e7-8492-b8d6d0e44086.png)

This on an emulator with API level 22
![screenshot_api_22](https://user-images.githubusercontent.com/12898752/27430864-803f9930-574a-11e7-88ec-a6548ff76ef8.png)

What I am surprised to see is that no one is apparently talking about this issue ...

**Comment by vanniktech** [comment]
Does it work on devices? I think I remember something vaguely about the simulator / emulator causing a few problems regarding the keyboard.

Also have you enabled showing the keyboard? By default it might be off on simulators.

> What I am surprised to see is that no one is apparently talking about this issue ...

Seems like you're the only one having that issue :D

**Comment by 70nyIT** [comment]
thanks @vanniktech 
I have never run into the issue with the keyboard. On API Level 21 and under, if you allow input also from the PC keyboard, that messes up everything and the soft keyboard doesn't show up even if forced. Disabling it has the emojis keyboard showing and working as expected since also the soft keyboard shows up.
Thanks for your patience!
