### ISSUE TITLE
In place Dialog when typing in :emoji-alias: into EmojiEditText

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#144]
This would be optional and configurable on the EmojiEditText and could look something like this (taken from Slack):

![screenshot_20170623-150502](https://user-images.githubusercontent.com/5759366/27483398-7d6848f2-5825-11e7-85ab-fa5fcffd1d3b.png)

Relates to #102

**Comment by rubengees** [comment]
The dataset the `generator` module uses, provides this information.
:grin: for example has the shortname `:grinning:` (This seems to differ a bit from other services, GitHub uses `:grin:` for that).
I can extend the `generator` to include this information into the `Emoji` object if you like.

**Comment by vanniktech** [comment]
That would be handy as a first step, yes. Although I think some emojis have more than one aliases. So maybe `Set<String>` or `String[]` is the way to go.

**Comment by rubengees** [comment]
Yes, the dataset provides those as `alias_alternatives` I think. There are also `keywords`, I will examine later what would make sense in this case and report back.

**Comment by runegame** [comment]
When I send an emoji from the web, I receive it in this way (see image) is there any way to see the emoji?
![image](https://user-images.githubusercontent.com/3906550/32744355-9cc0197a-c885-11e7-885a-1b44877298ce.png)

**Comment by vanniktech** [comment]
Don't hijack issues please.

**Comment by vanniktech** [comment]
@rubengees have you had time to getting around including the aliases / keywords from the website?

**Comment by rubengees** [comment]
@vanniktech Sorry, totally forgot about that!

I have pushed [a commit](https://github.com/rubengees/Emoji/commit/6504040219636433b00a74312d8bc534cb17e769) onto my fork with changes that implement this.
I will wait with a PR though, since we can't rerun the `generator` yet due to EmojiOne not having updated their `emoji.json` file yet...

**Comment by vanniktech** [comment]
Oh right. That's still missing.

**Comment by vanniktech** [comment]
Might happen or not. Will close for now.

**Comment by vanniktech** [comment]
I really want this. @rubengees what's the easiest way we can get the tags? Once we have them we can build some UI.

**Comment by rubengees** [comment]
I can do a PR for the tags I think.

**Comment by vanniktech** [comment]
Much appreciated!

**Comment by mario** [comment]
Where are we with this? :D

**Comment by vanniktech** [comment]
We've got the text, no dialog yet.
