### ISSUE TITLE
How to use Default Google/System Emojis?

### ISSUE THREAD

**Issue by searchy2** [vanniktech/Emoji#155]
I am relatively new to using this library so this question is likely due to a misunderstanding. 
Referencing the line in the ReadMe: 

> All of the core API lays in, which is being pulled in automatically by the provides implementations (iOS, EmojiOne & Google):

How is it possible to use default system emojis? In the ReadMe, only iOS and EmojiOne emojis are detailed. If it is not possible to use default system emojis out of the box, I would like to update the ReadMe to provide additional clarification. 

Thank you for this great library!

**Comment by vanniktech** [comment]
You can use `com.vanniktech:emoji-google:0.5.0-SNAPSHOT`

**Comment by searchy2** [comment]
Wow, thanks for the quick reply. Very helpful!

**Comment by searchy2** [comment]
Quick question, how can I get the snapshot please? What Maven dependency do I need to include in gradle?

**Comment by vanniktech** [comment]
`maven { url "https://oss.sonatype.org/content/repositories/snapshots" } `

**Comment by searchy2** [comment]
Thank you so much!
