### ISSUE TITLE
How to Customize Emoticon Builder Color

### ISSUE THREAD

**Issue by searchy2** [vanniktech/Emoji#156]
Referencing #70 Make Colors Customizable
How to customize the colors? There does not appear to be a XML attribute and I cannot find the method call to use. I would like to change the highlighted tab color to match my app better. 
![maxthonsnap20170628103824](https://user-images.githubusercontent.com/19896174/27646332-f474c31e-5bed-11e7-98b4-79cad4c54b8e.png)

**Comment by vanniktech** [comment]
It's the accentColor.

**Comment by searchy2** [comment]
Doh, should have realized that! What about the unselected icon colors and background/divider?

**Comment by vanniktech** [comment]
Predefined and they're configurable. @rubengees did a PR for that a while ago, #70

**Comment by searchy2** [comment]
Got it, just set the color values in your colors.xml with the same names and they will override the library colors.

`    
    <color name="emoji_background">#ECEFF1</color>
    <color name="emoji_icons">#61000000</color>
    <color name="emoji_divider">#15000000</color>`

**Comment by hvar90** [comment]
> It's the accentColor.

why is no posssible change that color on different way ? 

like on this way 
  
    <color name="emoji_background">#ECEFF1</color>
    <color name="emoji_icons">#61000000</color>
    <color name="emoji_divider">#15000000</color>

**Comment by vanniktech** [comment]
Dunno. If I were you, I'd use the builder

**Comment by hvar90** [comment]
> Dunno. If I were you, I'd use the builder

where is explained how change the colors using the bulder?

**Comment by vanniktech** [comment]
EmojiPopup.Builder

**Comment by hvar90** [comment]
> EmojiPopup.Builder

oh ok
i will use the builder 
thanks
