### ISSUE TITLE
Create New Emoji Popup Offset

### ISSUE THREAD

**Issue by searchy2** [vanniktech/Emoji#159]
In some custom configurations, the calculated height of the keyboard is not accurate. This leads to the emoji popup not overlapping the keyboard. 

![emoji popup too short](https://user-images.githubusercontent.com/19896174/27670642-dd498b14-5c53-11e7-99d8-5f0fd6e00b27.png)

![emoji popup animated](https://user-images.githubusercontent.com/19896174/27670817-fc7470fc-5c54-11e7-91e7-7117a757b81b.gif)

In my situation, I have some complex window hierarchies including no actionbar, immersive mode, and other libraries interacting with the view. The simplest solution is to create an offset to manually adjust the height of the Emoji Popup. 

PR #158

**Comment by vanniktech** [comment]
I'm surprised it does not work out of the box. Is one of your libraries doing something they should not?

**Comment by vanniktech** [comment]
Could the height difference be the status bar at the top that won't be displayed? If so the library should recognize this and adjust the height. (If it does not do this already)

**Comment by vanniktech** [comment]
See the comment in your PR #158.
