### ISSUE TITLE
Emoji Layout Incorrect Calculation On Initialization

### ISSUE THREAD

**Issue by searchy2** [vanniktech/Emoji#160]
When Emoji Popup is shown the first time, the first 2 screens (Recent, People) do not display emojis in the correct layout. After switching to the 3rd screen, the 3rd screen displays correctly. Switching back causes the initial screens to display correctly as well. 
Based on my understanding of the view pager, the first 2 layouts are initialized and something in the calculation is not initializing correctly. The 3rd pager displays correctly because it has not been initialized yet. When the first 2 pages are refreshed (and recalculated) they display correctly.
Unfortunately, I have been unable to reproduce this behavior in the sample project so it appears to be specific to my project. 
![emoji squeezed](https://user-images.githubusercontent.com/19896174/27671261-42336e24-5c58-11e7-9e6f-62e90f0e4768.gif)
Notice that the initial emoticon layout has 11 icons in a row. The correct layout only has 10. 
Any idea what might be the cause? I am thinking about creating a method to manually set the number of emoticons on each row to avoid errors in calculation.

**Comment by vanniktech** [comment]
On what device are you testing this?

Also this seems to correct to me. The first tab is the tab that contains the Emojis that you used recently.

The only thing that does seem buggy is the fact about 11 / 10 emojis per row.

**Comment by searchy2** [comment]
I am using an Xperia X Performance. However, the device is not the issue. I have compile the sample project on the same device and it does not have that behavior.

The first tab is supposed to contain recent emojis. That is correct. 

Look at where the arrow is pointing in the GIF. There is a space (padding?) that is not there. Only after the pager is refreshed does it appear. How are the number of emojis per row calculated? Could it be possible to have fewer emojis per row but make them bigger?

**Comment by vanniktech** [comment]
GridView takes care of lay-outing them. ` I have compile the sample project on the same device and it does not have that behavior.` which basically says that your app consuming this library is the problem, right?

**Comment by searchy2** [comment]
Yes, my app must have something interfering with the calculations. This is why I am looking into creating a way to manually set the # of icons per row. This would also enable the GridView to adjust the size of the emojis. Currently, the emojis are a bit too small for me.

**Comment by vanniktech** [comment]
Setting a size for the emojis in the displayed Gridview sounds reasonable. Changing the numbers shown per row is not something that I want in the API.

**Comment by vanniktech** [comment]
Created #173 for the emoji size customization for the popup.
