### ISSUE TITLE
RecentEmojiManager leaks

### ISSUE THREAD

**Issue by rubengees** [vanniktech/Emoji#164]
- Version of the library: Latest Snapshot (cf6b2169297010bcb3552f0f7bc08b28fabe696c)
- Affected devices: All
- Affected versions: Tested on `7.1.2`

This is the leak trace from `leakcanary`:

```
* GC ROOT static com.vanniktech.emoji.RecentEmojiVariantManager.INSTANCE
* references com.vanniktech.emoji.RecentEmojiVariantManager.variantListeners
* references java.util.HashMap.table
* references array java.util.HashMap$HashMapEntry[].[1]
* references java.util.HashMap$HashMapEntry.value
* references com.vanniktech.emoji.EmojiImageView$1.val$clickListener (anonymous
  implementation of com.vanniktech.emoji.RecentEmojiVariantManager$EmojiVariantListener)
* references com.vanniktech.emoji.EmojiPopup$3.this$0 (anonymous implementation
  of com.vanniktech.emoji.listeners.OnEmojiClickedListener)
* references com.vanniktech.emoji.EmojiPopup.onEmojiPopupDismissListener
* <my code>
```

This seems to happen due to the variant listeners which never get cleaned up.

**Comment by vanniktech** [comment]
They do. When the view is detached from the view. Although I probably should have changed the Singleton and create it the same way that the recent manager is created.

**Comment by rubengees** [comment]
Does Android call `onViewDetachedFromWindow` after destroying the `Fragment`/`Activity`? I get these leaks every time after I close my `Activity` with the `EmojiPopup`.

I am currently looking into a solution without `RecentEmojiVariantManager` being a singleton and without the map of listeners.

**Comment by vanniktech** [comment]
I already have an idea how to fix it and I'll do it this weekend (for sure).  A map of listeners you'll need.

**Comment by rubengees** [comment]
I have currently a working solution without that (though a bit ugly yet). If you don't object I'll send a PR and you can take a look.

**Comment by vanniktech** [comment]
Sure go for it.
