### ISSUE TITLE
update to version 0.5.1 and some colors are missing?

### ISSUE THREAD

**Issue by zoff99** [vanniktech/Emoji#175]
just updated from 0.4.0 to 0.5.1 and got these errors in android studio:

```
build-cache\e9664cde3a1b5fb0145d8cc52d56870240bb479c\output\res\layout\emoji_skin_popup.xml
Error:(7) No resource identifier found for attribute 'cardBackgroundColor' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardCornerRadius' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardElevation' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardUseCompatPadding' in package 'com.zoffcc.applications.trifa'
\app\build\intermediates\res\merged\debug\layout\emoji_skin_popup.xml
Error:(7) No resource identifier found for attribute 'cardBackgroundColor' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardCornerRadius' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardElevation' in package 'com.zoffcc.applications.trifa'
Error:(7) No resource identifier found for attribute 'cardUseCompatPadding' in package 'com.zoffcc.applications.trifa'
```

**Comment by rubengees** [comment]
Did you try to clean and re-build your project?

**Comment by ZonaRMR** [comment]
Same problem for me.

**Comment by vanniktech** [comment]
What build tools versions and support library version are you using? Also which version of the Android gradle plugin?

**Comment by zoff99** [comment]
the values are missing in the new version, can only fix by defining them in my project.

is the are migration document? (from 0.4.x -> 0.5.x)

**Comment by vanniktech** [comment]
Those values are defined in the support library.

**Comment by zoff99** [comment]
you sure? they start with "app:"
also if my app has to update to a minimum support lib version, please put this in the README.md

also this is bad! since it does not yet work with f-droid then

**Comment by zoff99** [comment]
i added this to my attrs.xml:

```
    <!-- for emoji 0.5.1 ?? -->
    <attr name="cardBackgroundColor" format="color"></attr>
    <attr name="cardCornerRadius" format="dimension"></attr>
    <attr name="cardElevation" format="dimension"></attr>
    <attr name="cardUseCompatPadding" format="boolean"></attr>
    <!-- for emoji 0.5.1 ?? -->
```

**Comment by vanniktech** [comment]
Just because they start with `app:` does not mean they're from the library. `android` is all android frameworks and since CardView is not in the Android Framework. It needs to be defined with `app:`

You still didn't tell me your versions of the tools & libraries :D

> forcing all apps that use this lib to the newest support lib will break some of them. (google maven repo)

I don't see this.

**Comment by zoff99** [comment]
```
    compile 'com.android.support:support-vector-drawable:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

    compile ('com.vanniktech:emoji-ios:0.5.1') {
        exclude group: 'com.android.support'
    }
```

**Comment by vanniktech** [comment]
Why `exclude group: 'com.android.support'`?

**Comment by zoff99** [comment]
i just said why, because i can't use the new google maven repo. so i need to use 25.3.1 for my app.
it's bad when libs force apps to use specific support library versions. especially when its not needed at all.
just for these 4 attrs?

**Comment by vanniktech** [comment]
You can still use `25.4.0` without the `google()` repo. Also why can't you add the `google()` repo?

**Comment by zoff99** [comment]
no matter.

i don't see a reason for a library to force all apps to use the latest support lib.

**Comment by rubengees** [comment]
You can also force a specific version, though a bit tedious: https://stackoverflow.com/a/36162210/4279995. 

Otherwise I would suggest to just keep using 0.4.0 or forking and changing the version if you *really* need a previous one. 

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by vanniktech** [comment]
Yeah exactly. Everyone is forcing you to a specific version in one way or another. Also it seems that the Google people did some changes that are not compatible with `25.4.0` and your `25.3.1`. You can file a bug on b.android.com.
