### ISSUE TITLE
To change the size of the displayed Emojis use the lineHeight property from TextView.

### ISSUE THREAD

**Issue by zoff99** [vanniktech/Emoji#179]
lineHeight -> there is no such property. can you give an example how to resize the emoji in a TextView, please?

lineSpacingMultiplier and lineSpacingExtra both do not resize the emoji

the only way now is to increase "textSize" property , which is not what i want.

**Comment by zoff99** [comment]
after playing around a bit i found:

app:emojiSize="40dp"

this will work. but it's not really documented

**Comment by vanniktech** [comment]
It is in the Readme and also in the sample app. Look at the sample how to achieve the effect of the screenshots in the Readme (single emoji really big, multiple emojis middle size and emoji + text normal size).

**Comment by zoff99** [comment]
i can't find it in the readme
