### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by cal2195** [vanniktech/Emoji#180]
Hey there,

Just wanted to let you know that the documentation in the read me is a little confusing! It sounds like you need to add both ```0.5.0``` and ```0.6.0-SNAPSHOT``` as a dependency! It's just one right?

I think it should be more clear!

Thanks,
Cal :)

**Comment by vanniktech** [comment]
Oh yes just one either the released one or if you prefer the SNAPSHOT.

**Comment by cal2195** [comment]
Awesome! Should probably say either dependency in the readme! 😄 

Thanks for the quick response! 👍

**Comment by vanniktech** [comment]
Alright might change it. :)
