### ISSUE TITLE
Error:(24, 13) Failed to resolve: com.vanniktech:emoji-google:0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by MeiYi2** [vanniktech/Emoji#183]
Hi.

I tried to include:

 `   compile 'com.vanniktech:emoji-google:0.5.1'
    compile 'com.vanniktech:emoji-google:0.6.0-SNAPSHOT'`

But it throws me this error: Error:(24, 13) Failed to resolve: com.vanniktech:emoji-google:0.6.0-SNAPSHOT.

Attach is the error image.

![screenshot 51](https://user-images.githubusercontent.com/10569370/28913356-51ba410a-786a-11e7-886c-6d6e57daae68.png)

Please advice.

Thank you.

**Comment by vanniktech** [comment]
Use only one and if you use the SNAPSHOT add the maven url.
