### ISSUE TITLE
Gradle issue

### ISSUE THREAD

**Issue by mechak** [vanniktech/Emoji#185]
Error:(41, 20) Failed to resolve: com.vanniktech:emoji-ios:0.6.0-SNAPSHOT
<a href="openFile:C:/Users/Steve Tchatchouang/AndroidStudioCanaryProjects/Choco-Messenger/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by vanniktech** [comment]
Add the maven url.

**Comment by mechak** [comment]
thanks

**Comment by mechak** [comment]
it works
