### ISSUE TITLE
Failed to resolve com.vanniktech:emoji-google:0.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by kkm** [vanniktech/Emoji#187]
Hello,
I want to try in gradle but I got this error. what does mean?
![Image of Yaktocat](http://capturei.tikatoy.com/r/mGEm.png)

thank you very much

**Comment by vanniktech** [comment]
Add the maven snapshot url.

**Comment by vanniktech** [comment]
Also dupe #183

**Comment by kkm** [comment]
Sorry for dupe but I dont know which snapshot url and can you show me example?

**Comment by vanniktech** [comment]
If you want you can also use just 0.5.0

**Comment by kkm** [comment]
Okay but which snapshot URL? please.

**Comment by kkm** [comment]
Why is so hard and I cant find Snapshot url from you?
thanks you for your reply.
