### ISSUE TITLE
Can you please increase the size of the emoji's in textView

### ISSUE THREAD

**Issue by anvesh523** [vanniktech/Emoji#19]
![emoji](https://cloud.githubusercontent.com/assets/10726276/14308812/38da0202-fbf6-11e5-9ff0-fecd08511db2.png)

In the editText the emoji's with text is perfect ....

But, after submit... In the textView the emoji's size is smaller than the text size...

**Comment by vanniktech** [comment]
There's a custom attribute which you can specify. Have a look [here](https://github.com/vanniktech/Emoji/blob/76a304ac19fd4f4fa828098e8938614f13facde5/app/src/main/res/layout/activity_main.xml#L43). If you change that value the emojis should get bigger.

Once you found the correct value I'm happy to accept a PR for the sample :)

**Comment by anvesh523** [comment]
@vanniktech  First thanks for the quick reply and for the _**Emoji**_. My problem solved. :+1:

**Comment by vanniktech** [comment]
@anvesh523 no problem :)

I'm curios though to which value did you change it?

**Comment by anvesh523** [comment]
I changed the values like 

EmojiEditText -> emojiSize : 26sp
EmojiTextView ->  emojiSize : 23sp

Previously EmojiTextView  I didn't specify any value, so by default it's coming small icons...

**Comment by vanniktech** [comment]
Okay cool. I'll close this then if you have any other issues let me know ;)

**Comment by anvesh523** [comment]
:100:     Sure  :+1:
