### ISSUE TITLE
Feedback Emoji bug

### ISSUE THREAD

**Issue by TCQQ** [vanniktech/Emoji#190]
If you inherit EmojiTextView in a custom TextView and do not display properly in the xml layout, the following error log

Exception Details java.lang.IllegalStateException: Please install an EmojiProvider through the EmojiManager.install() method first.   at com.changrui.tt.widget.emoji.EmojiManager.verifyInstalled(EmojiManager.java:184)   at com.changrui.tt.widget.emoji.EmojiManager.findAllEmojis(EmojiManager.java:154)   at com.changrui.tt.widget.emoji.EmojiManager.replaceWithImages(EmojiManager.java:130)   at com.changrui.tt.widget.emoji.EmojiTextView.setText(EmojiTextView.java:52)

**Comment by vanniktech** [comment]
That's not a bug that's an issue on your end you need to install a Provider. For instance using `EmojiManager.install(new IosEmojiProvider());`

**Comment by TCQQ** [comment]
But once you inherit it, the layout will not be displayed..

**Comment by vanniktech** [comment]
Please read the Readme thoroughly.

**Comment by gelbertgel** [comment]
I used 0.5.1 version. I have implemented EmojiEditText,EmojiTextView like you were showing. But i have same issue all android versions and devices. Please help me!!

` Background partial concurrent mark sweep GC freed 12157(903KB) AllocSpace objects, 62(7MB) LOS objects, 7% free, 195MB/211MB, paused 47.152ms total 985.443ms`
