### ISSUE TITLE
Background partial concurrent mark sweep GC

### ISSUE THREAD

**Issue by gelbertgel** [vanniktech/Emoji#192]
I use 0.5.1 version. I have implemented EmojiEditText,EmojiTextView like you were showing. But i have same issue all android versions and devices. Please help me!!

`Background partial concurrent mark sweep GC freed 12157(903KB) AllocSpace objects, 62(7MB) LOS objects, 7% free, 195MB/211MB, paused 47.152ms total 985.443ms`

**Comment by vanniktech** [comment]
What makes you think this is because of this library?

**Comment by gelbertgel** [comment]
Because app is freezing when passing through emoji pages and i take this error.

**Comment by vanniktech** [comment]
Do you have a sample or anything?

**Comment by gelbertgel** [comment]
I have calculated keyboard height for edittext max line. This is causing to freeze. Sorry.

**Comment by vanniktech** [comment]
Alright so I can close this?

**Comment by gelbertgel** [comment]
Yeap sorry again ::)

**Comment by vanniktech** [comment]
No worries
