### ISSUE TITLE
US emoji flag not rendering

### ISSUE THREAD

**Issue by yzheka** [vanniktech/Emoji#203]
- Library version 0.5.1
- Affects all devices
- Affects all versions

[Screenshot](https://prnt.sc/gk5n8g)

**Comment by vanniktech** [comment]
What's the unicode point?

**Comment by yzheka** [comment]
\uD83C\uDDFA\uD83C\uDDF8
There is the same problem with few others flags

**Comment by vanniktech** [comment]
Are you talking about this one 🇺🇸 ?

**Comment by yzheka** [comment]
yes

**Comment by vanniktech** [comment]
I just checked in the sample app and it works fine there. Hence I'm closing this. It looks like it's an issue on your end.

**Comment by kkm** [comment]
@yzheka Your mobile bans stuff of USA. e.g Flag
