### ISSUE TITLE
Memory leak detected using EmojiEditText

### ISSUE THREAD

**Issue by ricamgar** [vanniktech/Emoji#216]
Hi! I am getting a memory leak reported by LeakCanary on an Activity where I use the EmojiEditText on the layout xml.

The element looks like this:
![image](https://user-images.githubusercontent.com/927648/32314899-3ba7b92e-bfaa-11e7-9a3e-1fe27841f043.png)

And this is the leak:
![image](https://user-images.githubusercontent.com/927648/32314820-f1044216-bfa9-11e7-9496-6cce49b7da17.png)

The library version is: 0.5.1
The api version is 25

Thanks!

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
I'd assume this is coming from the Android Profiler in Studio 3.0 since one of the package names is indicating that.

**Comment by ricamgar** [comment]
Yes, I'm using AS 3.0.

**Comment by vanniktech** [comment]
I'm fairly certain this is caused by the new profiler. If this memory leak still occurs in release builds, please reopen the issue.

**Comment by chim0380** [comment]
**LeakCanary** detect memory leak when sleect several emoji in popWindow and rotate device after this (recreate activity).
