### ISSUE TITLE
Add additional tabs to keyboard

### ISSUE THREAD

**Issue by holysheep** [vanniktech/Emoji#218]
Is it possible to insert stickers tab in emoji keyboard?

**Comment by vanniktech** [comment]
For sure.

**Comment by vanniktech** [comment]
Just for the record you can already place your own categories with your own emojis by implementing your own Provider and delegating to a standard one for the first few tabs.

**Comment by ThangPk** [comment]
@vanniktech When will be there a next release including this feature?  Thanks.

**Comment by vanniktech** [comment]
Someone has to implement it first.

**Comment by vanniktech** [comment]
Decided that this is slightly out of the main purpose - Emojis - of this library. Hence I'll close this. I believe that I've seen some solutions that offer both solutions (Emoij + Stickers) in one.

**Comment by 3llomi** [comment]
@vanniktech i am working on adding a 'Stickers' tab, if you are interested i can make a PR, otherwise i would make my own fork if you are okay with that

**Comment by vanniktech** [comment]
I'd be interested in stickers; though they'd need to live in their own artifact. Would you be open for that idea?

**Comment by 3llomi** [comment]
@vanniktech Yeah,sure, so it would be like 'emoji-with-stickers' for example right?

**Comment by vanniktech** [comment]
Just, `emoji-stickers`.

**Comment by 3llomi** [comment]
#453 @vanniktech  please check the PR out.

**Comment by nAkhmedov** [comment]
It would be better to add ability extra tabs.
