### ISSUE TITLE
OnGlobalLayoutListener may cause performance degrade

### ISSUE THREAD

**Issue by GreenSkinMonster** [vanniktech/Emoji#22]
First, thanks for your awesome module.
I used it in my app, and it works very well.

But it may cause performance issues on some devices, in my case, Moto X Style with CM 13 (Android 6.0.1), but not with my Galaxy S4 (Android 4.4), LG G2 (Android 5.0).
And many users reported too, mostly Android 6.0.

The issue:
I have some fragments with EmojiPopup instance, after start and exit those fragments couple times, ListView scrolling skipped a lot, also with SwipeRefreshLayout pull to refresh action.

I checked setSizeForSoftKeyboard function, and found OnGlobalLayoutListener was attached to rootView but never removed. So rootView could be attached multiple listeners, cause performance degrade.
https://github.com/vanniktech/Emoji/blob/master/library/src/main/java/com/vanniktech/emoji/EmojiPopup.java#L142

So I hacked a little, remove OnGlobalLayoutListener  on fragment destory.
Which solved my problem.

But I don't think it's a clean way to do it.
Maybe OnGlobalLayoutListener should be removed when measure is done?

Thanks.

**Comment by vanniktech** [comment]
Hey sorry for not answering earlier. Haven't gotten that much time lately.

Thanks for filing the issue. I'll dig into this issue and see what the library can do. In any case the consumer should not worry about removing the listener.

**Comment by vanniktech** [comment]
@GreenSkinMonster for now please use the SNAPSHOT version I'll try to get a version out in the next days

**Comment by vanniktech** [comment]
@GreenSkinMonster I just released version `0.3.0` which contains the fix. Thanks again!

**Comment by GreenSkinMonster** [comment]
I tested with version 0.3.0 , found another issue.

Say we start a fragment, and it contains a EmojiEditText at bottom.
EmojiEditText request focus onCreateView, and soft keyboard shows after view created.

But OnGlobalLayoutListener is not attached to rootView yet, so keyBoardHeight is still 0 .
If user press the toggle button, it won't switch to EmojiView.

If we attach OnGlobalLayoutListener in onCreateView like before, which works fine.

Maybe OnGlobalLayoutListener should be attached onCreateView, then remove when it get keyBoardHeight the first time? Then re-attach at toggle, remove when dismiss?

In my code, I hacked somehow to store user's last keyBoardHeight value, so we could get keyBoardHeight on the first use if OnGlobalLayoutListener is not attached. 

But I'm not sure what's the proper way. 

If you want to check my hacked version, it's here
https://github.com/GreenSkinMonster/hipda/blob/8ba40b5e0469f9cdd622ecd1c4000b17a4dbc6f6/emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java

**Comment by vanniktech** [comment]
So basically what you're saying is that the `Listener` needs to be added to the `rootView` again in the constructor, because the first time it does not work?!

**Comment by GreenSkinMonster** [comment]
Yes, I think so.

**Comment by vanniktech** [comment]
Hmm I just tried it again and I don't see that we need this though I can't say for sure that it currently works on all platforms & devices.

Another option would be keep the `add` in the constructor and introduce a new method on the `EmojiPopup` like `destroy()` which would be called when the popup will be destroyed and in there the `Listener` would be removed.
