### ISSUE TITLE
Some UI artifact while fast scrolling

### ISSUE THREAD

**Issue by yshubin** [vanniktech/Emoji#221]
- Version of the library: 0.5.1
- Affected devices: Nexus 5
- Affected versions: 5.0.1

![device-2017-11-22-180708](https://user-images.githubusercontent.com/6691617/33135018-566c27be-cfb2-11e7-86a4-a90defc416e7.jpg)

**Comment by vanniktech** [comment]
Thanks for fixing this in #223 :)
