### ISSUE TITLE
Emoji popup appearing above keyboard

### ISSUE THREAD

**Issue by daniele-athome** [vanniktech/Emoji#224]
I'm using version 0.5.1 and I'm experiencing what this user reported on my project:
https://github.com/kontalk/androidclient/issues/1110

I also tested the sample app in your library on my device (even with a different keyboard) and got the same result:

![device-2017-12-03-201836](https://user-images.githubusercontent.com/3763726/33528805-642c170c-d867-11e7-8e8e-677589c92f8b.png)

It happens with [Taskbar](https://f-droid.org/app/com.farmerbb.taskbar) installed, but I guess it might happen with other apps drawing stuff over other windows.

I also tried [forcing popup repositioning](https://github.com/kontalk/Emoji/commit/1ebf757c0ec7994d523ff0684e28a4081bdbe058) and [setting a gravity](https://github.com/kontalk/Emoji/commit/a92c479a9313e3ae66268c1647c0dd0fc9994219) but neither worked.

Thanks for this great library! [I proudly showed it on our latest release post](https://forum.kontalk.org/t/kontalk-4-1-1-new-emoji-set/400?u=daniele_athome) :-)

**Comment by vanniktech** [comment]
Sorry for not getting to this earlier.

What's the device? 

Have you also tried setting both? (Forcing & gravity)

**Comment by daniele-athome** [comment]
I'm on a Moto X XT1052 running a stock Motorola firmware, Android 5.1. The user reporting this is also running Android 5.1.

Yes, I've tried either indipendently and both toghether. It seems that calling update() on the PopupWindow has no effect at all.

**Comment by vanniktech** [comment]
Is this device specific?

**Comment by daniele-athome** [comment]
Most probably not, I have the Motorola I mentioned before, the reporting user has a Huawei Nova with Android 7. It isn't even an Android version specific issue I'm afraid.

**Comment by vanniktech** [comment]
I'll close this in favor of #191.
