### ISSUE TITLE
Feedback Emoji Problem

### ISSUE THREAD

**Issue by tcqq** [vanniktech/Emoji#234]
Hello, when the theme is switched to night, the background color will not change, 
how to customize： 

emoji icon selected color
emoji icon normal color
emoji popup background color
emoji popup divider color

hope can support, thank you.

**Comment by vanniktech** [comment]
You can try overriding those.

**Comment by TCQQ** [comment]
But I want to reference this library via gradle, this is easy to use

**Comment by TCQQ** [comment]
You provide setColor method alright? thank you

**Comment by vanniktech** [comment]
Just override the Android resources.

**Comment by TCQQ** [comment]
But applying theme support customization, I had to change it programmatically

**Comment by vanniktech** [comment]
But your problem is solved?

**Comment by TCQQ** [comment]
No, I am currently using the Gradle add library

**Comment by vanniktech** [comment]
You can override the Android resources in your app.

**Comment by TCQQ** [comment]
You help me add a setColor method for this library alright? This feature is commonly used, this feature is useful.

**Comment by TCQQ** [comment]
You configured the nighttime mode color correctly, but the library does not change color when you switch to night mode
![image](https://user-images.githubusercontent.com/10644057/34475397-b62c8e94-efc6-11e7-97b8-00006b14af97.png)
![image](https://user-images.githubusercontent.com/10644057/34475418-f26b27a8-efc6-11e7-9901-49e12501ad22.png)
![image](https://user-images.githubusercontent.com/10644057/34475419-f5743bba-efc6-11e7-9b28-b7eeb185eeaf.png)

**Comment by vanniktech** [comment]
Closing this as there's already an open PR for this. Feel free to continue on the PR - I left some feedback there.
