### ISSUE TITLE
Where is Unicode Cheat sheet ?

### ISSUE THREAD

**Issue by khalid-mahmood** [vanniktech/Emoji#238]
how i can set my desired icons without using popup window ?
Just added this in xml
    <com.vanniktech.emoji.EmojiTextView
        android:id="@+id/adapter_chat_text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textIsSelectable="true"
        app:emojiSize="32dp"
        />
gradle dependancy
compile 'com.vanniktech:emoji-google:0.5.1'

App 
    @Override
    public void onCreate() {
        super.onCreate();
        EmojiManager.install(new GoogleEmojiProvider());

    }
what to do next to render emoji in layout ?

**Comment by vanniktech** [comment]
https://unicode.org/emoji/charts/full-emoji-list.html
