### ISSUE TITLE
Need Public Function

### ISSUE THREAD

**Issue by SY102134** [vanniktech/Emoji#243]
I want to use it on react native app, 
I need:
1. replaceWithImages function(public static) to custom my Text or TextInput;
2. emoji view panel(public class, onClickEmojiListener, onClickEmojiBackspaceListener), only view not a PopupWindow View

Thanks!!!

**Comment by vanniktech** [comment]
Why can't you use the public api just like anyone else?

**Comment by SY102134** [comment]
@vanniktech 

In the react native application I can simply set the style through javascript, have a public replaceWithImages function, I just need to replace the text; if use public api (EmojiEditText, EmojiTextView...), I need to export the module, React component is useless, and there is no perfect React component(Text、TextInput).
If you provide a public emoji panel(new EmojiView), We can custom editText, We can use it anywhere, not just on the keyboard.

Change a type, the library has more freedom.

**Comment by vanniktech** [comment]
Why can't you just use the native types on android? And then write some wraper in react. Plus how would you do things with iOS?

**Comment by SY102134** [comment]
React has written the wraper, I just need to replace text, It would not be necessary if I had to write some wraper, and I did not write well. Ios I did not consider, if ios performance well, I can use js to write

**Comment by vanniktech** [comment]
So you basically only need the replaceWithImages function to be public and nothing else?

**Comment by SY102134** [comment]
@vanniktech 
ReplaceWithImages function and a Emoji Panel,
Emoji Panel (new EmojiView()) has onClickEmojiListener and onClickEmojiBackspaceListener

This is a panel of modifying your code.
![screenshot_2018-01-25-22-46-53](https://user-images.githubusercontent.com/18373625/35394468-d1ecdd64-0222-11e8-803a-77dacb4e8c39.jpeg)

**Comment by SY102134** [comment]
@vanniktech 
EmojiPanel like EmojiPopup, but not in popupWindow,
The EmojiPopup has some events, EmojiPanel  also have!

**Comment by vanniktech** [comment]
Can you come up with a PR that changes the things you really need to be public? Idieally this should be 3-5 lines since it'll only change the modifiers to be public.

I've lost context and don't see what exactly you need.

**Comment by SY102134** [comment]
ok, After I submitted a pr!
