### ISSUE TITLE
Update Emojis

### ISSUE THREAD

**Issue by Gaetano-Dati** [vanniktech/Emoji#245]
What a nice library. 
Anyway I noticed that Emojis are a little older than WhatsApp ones. Is there a way to update all Emojis in this library everytime they're updated in WhatsApp?
Thanks

**Comment by vanniktech** [comment]
Dupe of #227.

We rely on the ordering of the emojis from emojione and they haven't fixed theirs yet - https://github.com/emojione/emojione/issues/523

**Comment by Gaetano-Dati** [comment]
But do they update automatically or  do I have to change number of dependency version?@vanniktech

**Comment by vanniktech** [comment]
They don't update automatically. I'll need to update them in the sources and then publish a new version.
