### ISSUE TITLE
Is it possible to delete Log.d at sample MainActivity -> setUpEmojiPopup()?

### ISSUE THREAD

**Issue by munirbraganca** [vanniktech/Emoji#253]
Hello, I want to delete the logs of my app before publishing, so, how to remove this Log.d:

emojiPopup = EmojiPopup.Builder.fromRootView(rootView)
        .setOnEmojiBackspaceClickListener(ignore -> **Log.d**(TAG, "Clicked on Backspace"))
        .setOnEmojiClickListener((ignore, ignore2) -> **Log.d**(TAG, "Clicked on emoji"))
        .setOnEmojiPopupShownListener(() -> emojiButton.setImageResource(R.drawable.ic_keyboard))
        .setOnSoftKeyboardOpenListener(ignore -> **Log.d**(TAG, "Opened soft keyboard"))
        .setOnEmojiPopupDismissListener(() -> emojiButton.setImageResource(R.drawable.emoji_ios_category_people))
        .setOnSoftKeyboardCloseListener(() -> **Log.d**(TAG, "Closed soft keyboard"))
        .build(editText);

**Comment by vanniktech** [comment]
Just don't set the listener then? In any case the sample should be untouched.
