### ISSUE TITLE
how to hide the text keyboard?

### ISSUE THREAD

**Issue by flpanbin** [vanniktech/Emoji#254]
I used 'com.vanniktech:emoji-ios:0.5.1' version of this library.when i called the 'emojiPopup.toggle()' method,emoji keyboard and text keyboard displayed at the same time.But i just want to show the emoji key board. If i call the 'hideKeyBoard(context,edtText)' to hide the text keyboard after 'emojiPopup.toggle()' method,the emoji keyboard and text keyboard will be hidden.So i want to ask how to hide the text keyboard. 

The 'hideKeyBoard(Context context, IBinder token)' method  that i called as below:
`
      public static void hideKeyBoard(Context context, IBinder token) {

        InputMethodManager inputMethodManager = (InputMethodManager) 
         context.getSystemService(Context.INPUT_METHOD_SERVICE);
       inputMethodManager.hideSoftInputFromWindow(token,InputMethodManager.HIDE_NOT_ALWAYS);
    }`

Please help me,thanks!
----------------------------------------------------------------------

**Comment by vanniktech** [comment]
We currently fire up both to get the height of the keyboard so the emoji popup can be overlayed correctly. In #191 there was a discussion about separating it.

In either case this is working as intended for now. Feel free to contribute to the other issues and give some more insights.
