### ISSUE TITLE
Possible to display a popup / chooser with no text input?

### ISSUE THREAD

**Issue by antgel** [vanniktech/Emoji#256]
As in, a simple picker / chooser without editing text? Something that I'd be able to toggle / make visibility, and that would return the chosen emoji to the calling code?

Motivation: I'd like to implement https://github.com/RocketChat/Rocket.Chat.Android/issues/473.

**Comment by vanniktech** [comment]
That sounds quite useful and #144 could also benefit in some way from this. Do you have any ideas how to tackle it?

**Comment by antgel** [comment]
Unfortunately I don't know enough about it. For what it's worth, here's what the Rocket.Chat Android folks are doing: https://github.com/RocketChat/Rocket.Chat.Android/pull/759

**Comment by vanniktech** [comment]
This will be done with #144 and can already be achieved currently since from the `EmojiManager` you can get all of the emojis already.
