### ISSUE TITLE
possible bug of the Recent Emoji system ? 

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#257]
- Version of the library: 0.5.1
- Affected devices: samsung but i had a huawei and i had the same problem
- Affected versions: i have had this problem with all versions

![screenshot_20180220-115203](https://user-images.githubusercontent.com/3120114/36437444-facc29e4-1634-11e8-853a-e1f8096cc00c.png)

firs i have a initial list of Recent Emojis

![screenshot_20180220-115245](https://user-images.githubusercontent.com/3120114/36437445-fae8d6f2-1634-11e8-8f36-f7bcc5395abe.png)

when i put a new emoji that emoji is showed on the list of Recent Emojis
![screenshot_20180220-115300](https://user-images.githubusercontent.com/3120114/36437446-fb99c9e4-1634-11e8-8969-cd242ceb804d.png)
but when i close the activity and open again the chat activity the new emoji is not on the list of  Recent Emojis, so, the new emojis are not presistent, that is the problem 

is this a bug ? or i need do some configuration, i want the same system of Recent Emojis like whatsapp

**Comment by vanniktech** [comment]
I think the emojis are not saved when you leave the activity but don't manually dismiss the emoji popup.

This issue, #110 is also related. Feel free to fix this issue yourself.

**Comment by hvar90** [comment]
oh, very easy to resolve, just is necessary  manually dismiss the emoji popup
thanks for the explanation

**Comment by vanniktech** [comment]
So this can be closed?

**Comment by hvar90** [comment]
yes, it can
if someone have this problem can do the dismiss on onStop or onDestroy function of the activity 
```
    @Override
    public void onStop() {       
        if (emojiPopup != null && emojiPopup.isShowing())
            emojiPopup.dismiss();
        super.onStop();
    }
```
