### ISSUE TITLE
Sprite image limitation

### ISSUE THREAD

**Issue by orenoren** [vanniktech/Emoji#258]
The change to using a sprite image "sheet.png" is most welcome, BUT now there is no way to update only some of the emojis with my own. 
There should be an tool included, which combines the emojis pngs to the sprite image "sheet.png", or this should be a part of the build.

**Comment by vanniktech** [comment]
You can get some tooling out from the javascript file which does all of the heavy lifting - https://github.com/vanniktech/Emoji/blob/master/generator/index.js
There's also [glue](https://github.com/jorgebastida/glue) and other tools such as convert which can help there.

**Comment by orenoren** [comment]
But the emojis pngs are not included in the latest version, and the newest emojis are not included in any other previous version.
Do you have a version with the latest emojis and without the sprite image?

**Comment by vanniktech** [comment]
Nope.
