### ISSUE TITLE
EmojiOne regression?

### ISSUE THREAD

**Issue by stefanhaustein** [vanniktech/Emoji#259]
Hi, could there be a recent regression in 6.0-SNAPSHOT wrt. EmojiOne images? Several Emoji seem to be missing (boxed button-like arrows, skull&bones), and the Emoji look like EmojiOne 2 (opposed to EmojiOne 3)? 

Perhaps related to the recent change to sprite sheets? 

I'd revert to 5.1 for now, but I can't because that pulls in an older version of the design or support library...

**Comment by vanniktech** [comment]
You can override the versionf of design + support library. As for the missing images, I'd refer to @rubengees

**Comment by rubengees** [comment]
@stefanhaustein You are right, did not notice that while testing as I am not using EmojiOne in any of my apps. We are now using this [data source](https://github.com/iamcal/emoji-data) which does not not have the latest EmojiOne emojis and there is already an [open issue](https://github.com/iamcal/emoji-data/issues/85) + [open PR](https://github.com/iamcal/emoji-data/pull/132) for that, so you can watch those for updates if you like.

If you want to use the previous version without going all the way back to `0.5.1`, you can use this dependency from [JitPack](https://jitpack.io/#vanniktech/Emoji): `com.github.vanniktech:Emoji:7f7f35c3e7`

**Comment by stefanhaustein** [comment]
Thanks,  ```compile 'com.github.vanniktech.Emoji:emoji-one:7f7f35c3e7' ``` seems to work for now....

**Comment by rubengees** [comment]
@vanniktech Yes! I'll try to find time to do that shortly.
