### ISSUE TITLE
shows above keyboard in dialog box

### ISSUE THREAD

**Issue by soban-shareviasms** [vanniktech/Emoji#26]
I have a dialog box in which user can enter text and emoji.
But when i open emoji panel it shows above the keyboard instead of top of the keyboard.
I have given root view of the dialog box custom xml root view

**Comment by vanniktech** [comment]
Hey there which version are you using and also can you provide a screenshot of the issue?

**Comment by soban-shareviasms** [comment]
![screenshot_2016-05-02-17-22-14](https://cloud.githubusercontent.com/assets/13640323/14954503/4f4ff8e8-108c-11e6-91c3-78f50cec31d2.png)
![_20160502_173530](https://cloud.githubusercontent.com/assets/13640323/14954509/5b8c07fa-108c-11e6-910f-4d88a5069152.JPG)

0.1

**Comment by vanniktech** [comment]
Yup that's true. I just verified it and there's no support for dialogs. Since I'm not using this library with dialogs and right now I don't have any particular need for that, I won't fix this for now though I'd be open for PRs.

**Comment by soban-shareviasms** [comment]
I successfully resolved this issue by changing the value of y axis.

`private void showAtBottom() {
        popupWindow.showAtLocation(rootView, Gravity.BOTTOM, 0, -700);
    }`

**Comment by vanniktech** [comment]
Where is that `-700` coming from? It might fit your device but not different devices.

**Comment by soban-shareviasms** [comment]
Yes, for my device, But we can calculate the distance between bottom of dialog to the bottom of mobile screen.

**Comment by vanniktech** [comment]
That number could also be a parameter of the builder so when you construct your EmojiPopUp you can pass the value you want and then as the consumer you'd need to calculate it. Default value would still be 0 though.

**Comment by soban-shareviasms** [comment]
Yeah it will be good.
Kindly add this.
