### ISSUE TITLE
Problem in the languages ​​right to left

### ISSUE THREAD

**Issue by tikestan** [vanniktech/Emoji#263]
Problem in the languages ​​right to left. please help

Device language rtl
![screenshot_ - - - - -](https://user-images.githubusercontent.com/29945866/37075276-4e99696c-21e6-11e8-998a-50ccce693de5.png)

----------------------------------------------------------------------
Device language ltr
![screenshot_2018-03-07-08-46-41](https://user-images.githubusercontent.com/29945866/37075337-a3410f2e-21e6-11e8-8797-7cfd74ad40fd.png)

Please help me thanks.

**Comment by vanniktech** [comment]
Oh that can definitely be fixed. Wanna take a stab at it?

**Comment by vanniktech** [comment]
Working for me in the sample app.

![1537896977](https://user-images.githubusercontent.com/5759366/46031830-4b26ef80-c0fa-11e8-9a61-eb11f0507eeb.png)
