### ISSUE TITLE
Why is the shape of some emoji different in pop-ups with what is displayed in the textview?

### ISSUE THREAD

**Issue by palize** [vanniktech/Emoji#269]
![emoji](https://user-images.githubusercontent.com/2226899/37257516-b2411d74-257f-11e8-84b0-eace5832536e.png)

**Comment by vanniktech** [comment]
Are you using EmojiTextView there?

**Comment by palize** [comment]
yes i use it.

**Comment by palize** [comment]
ok. for send i use EmojiTextView, but in receive layout was textview.
thanks
