### ISSUE TITLE
Both Emoji KeyBoard and character Keyboard opens at same time 

### ISSUE THREAD

**Issue by iPramodSinghRawat** [vanniktech/Emoji#282]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Dupe of #191
