### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by rocboronat** [vanniktech/Emoji#289]
The last release is one year old. And lots of work has been done since then.

May you launch a new release? I know that we could use snapshots or even jitpack, but it's hard to guess if the last release is stable or not.

Thanks a lot! And congrats for your work. I met you in https://github.com/rockerhieu/emojicon/pull/98 😅

**Comment by vanniktech** [comment]
There's still this issue #275 which I'd like to be fixed first since it was introduced in the meantime. Feel free to help out as I'm swamped with other things.

**Comment by rocboronat** [comment]
Thbks for that quick answer! Impressive 😎
