### ISSUE TITLE
Library doesn't offer a AutoCompleteTextView that supports emojis

### ISSUE THREAD

**Issue by rocboronat** [vanniktech/Emoji#290]
As we want to offer an EditText that also autocompletes when user mentions when user types an "@", we need an `EmoijAutoCompleteTextView`.

As we are migrating from https://github.com/rockerhieu/emojicon to here, we find this kind of lacks.

BTW, thanks for the good work!

**Comment by vanniktech** [comment]
Feel free to open a PR.

**Comment by rocboronat** [comment]
Totally :·)

**Comment by EsteveAguilera** [comment]
@rocboronat just a reminder that we're using a `MultiAutoCompleteTextView` 😜

**Comment by rocboronat** [comment]
Thathathathanks!! 🙆🏻‍♂️

**Comment by rocboronat** [comment]
Work in progress at #292

**Comment by vanniktech** [comment]
This can be closed now. Thanks for the contribution.

**Comment by rocboronat** [comment]
😁
