### ISSUE TITLE
Project doesn't build as soon as we clone it

### ISSUE THREAD

**Issue by rocboronat** [vanniktech/Emoji#291]
Right now, the project asks to configure the `mavenPublish` task. May we offer a fake configuration to welcome collaborators that don't care about releasing versions?

`Error:Please configure repositoryUsername via mavenPublish.repositoryUsername or alternatively set the Gradle / System environment variable SONATYPE_NEXUS_USERNAME`

In addition, the project references `apply plugin: "com.vanniktech.maven.publish"` that breaks my head.

**Comment by vanniktech** [comment]
Oh yes. Update that dependency to 0.4.0 please.

**Comment by rocboronat** [comment]
Thanks for the quick answer :·)

**Comment by vanniktech** [comment]
Sorry for the inconveniences.

**Comment by rocboronat** [comment]
Wop, it also crashes.

You mean this dependence, isn't it?
`classpath 'com.vanniktech:gradle-maven-publish-plugin:0.4.0'`
