### ISSUE TITLE
NullPointerException when try for getDrawable

### ISSUE THREAD

**Issue by saeedmozaffari** [vanniktech/Emoji#299]
Hi,
In android 4 when users try for get emoji from drawable following error will be occurred

![screenshot 8](https://user-images.githubusercontent.com/16954656/44943022-ccc57f00-add3-11e8-916d-010479f9ba51.png)

Also this error won't be occurred for all of users that use from android version 4 . So this error did not happen in my testing devices.

![screenshot 9](https://user-images.githubusercontent.com/16954656/44943033-12824780-add4-11e8-961c-8f4b153915b2.png)

exactly i use your library until this commit ['Add support for AutoCompleteTextView and MultiAutoCompleteTextView'](https://github.com/vanniktech/Emoji/commit/a3c52dc748a4f9e9d0ab2c21c388496a84dea23b)

- Version of the library: emoji-one:0.5.1
- Affected devices: sony , samsung , sony ericsson , huawei , ... 
- Affected versions: just android 4 (4.0.4 , 4.1.2 , 4.4.2 , 4.2.2)
----------------------------------------------------------------------

**Comment by vanniktech** [comment]
This will be deprecated / changed by #297
