### ISSUE TITLE
Recipient are getting blanks or weird characters

### ISSUE THREAD

**Issue by runner26** [vanniktech/Emoji#300]
Everything is working EXCEPT recipient are getting blanks or weird characters. Emoji appears ad working on Sender side, emoji appears on push notification but when recipient opens the message it's either blank or showing other characters like 3, /,?

**Comment by vanniktech** [comment]
Some more information?

**Comment by runner26** [comment]
Sorry I pretty new in coding what info you need?

So far emoji from sender are all working, the keyboard is ok and when sender send emoji it is working even the push notification display the emoji. But on the receiver side it is showing blank emoji or characters $,&<,3 etc.

my receiver_text_item.xml

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <RelativeLayout
        android:layout_width="match_parent"
        android:id="@+id/star_header"
        android:layout_marginTop="10dp"
        android:visibility="gone"
        android:layout_marginBottom="5dp"
        android:layout_height="wrap_content">

        <de.hdodenhof.circleimageview.CircleImageView
            android:layout_width="25dp"
            android:id="@+id/user_image_star"
            android:src="@drawable/ic_account_circle"
            android:layout_height="25dp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_marginTop="5dp"
            android:text="Sender"
            android:id="@+id/sender_star_text"
            android:layout_toRightOf="@+id/user_image_star"/>
        <ImageView
            android:layout_width="15dp"
            android:src="@drawable/ic_right_play"
            android:id="@+id/center_image"
            android:layout_marginTop="6dp"
            android:tint="@color/black"

            android:layout_toRightOf="@+id/sender_star_text"
            android:layout_height="15dp" />
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="5dp"
            android:layout_marginTop="5dp"
            android:text="Sender"
            android:id="@+id/receiver_star_text"
            android:layout_toRightOf="@+id/center_image"/>


        <ImageView
            android:layout_width="wrap_content"
            android:id="@+id/right_arrow"
            android:layout_alignParentRight="true"
            android:tint="@color/grey"

            android:src="@drawable/right_chevron"
            android:layout_height="wrap_content" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="3dp"
            android:text="13/15/2017"
            android:id="@+id/date_star"
            android:layout_toLeftOf="@+id/right_arrow"/>

    </RelativeLayout>


    <FrameLayout
        android:id="@+id/incoming_layout_bubble"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/star_header"
        android:layout_alignParentLeft="true"
        android:layout_marginLeft="8dp"
        android:layout_marginRight="60dp"
        android:background="@drawable/balloon_incoming_normal"
        android:padding="6dp">
        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:visibility="gone"
            android:id="@+id/remove_view_check"/>

        
        

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <TextView
                android:id="@+id/group_receiver"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:paddingLeft="12dp"
                android:textColor="@color/colorPrimaryDark"
                android:visibility="visible" />
            <LinearLayout
                android:layout_width="250dp"
                android:orientation="vertical"
                android:layout_marginTop="10dp"
                android:visibility="gone"
                android:layout_below="@+id/group_receiver"
                android:layout_marginLeft="10dp"
                android:id="@+id/parent_layout"
                android:layout_marginRight="10dp"
                android:layout_height="100dp">

            </LinearLayout>

            <com.vanniktech.emoji.EmojiTextView
                android:id="@+id/receiver_text_message"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/parent_layout"
                android:textColorLink="@color/link_blue"
                android:layout_marginRight="5dp"
                android:autoLink="web"
                android:paddingLeft="12dp"
                android:textAppearance="@android:style/TextAppearance.DeviceDefault.Small"
                android:textColor="@color/dark_gray"
                app:emojiSize="20dp" />





        </RelativeLayout>


        <TextView
            android:id="@+id/receiver_time_txt"
            style="@style/chat_timings"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|right"
            android:layout_marginRight="5dp"
            android:textSize="10sp"
            android:paddingLeft="6dp"
            android:text="11:15 PM" />
        <ImageView
            android:layout_width="12dp"
            android:layout_marginBottom="2dp"
            android:id="@+id/star_image"
            android:layout_height="12dp"
            android:layout_gravity="bottom|right"
            android:layout_marginRight="55dp"
            android:layout_marginLeft="5dp"
            android:src="@drawable/ic_grey_star"/>

        


    </FrameLayout>

</RelativeLayout>

**Comment by runner26** [comment]
![screenshot_2018-09-15-08-57-54-409_biz hashtag chat](https://user-images.githubusercontent.com/36129895/45580632-19c24e80-b8c6-11e8-89fc-744e37bb2107.png)
please help

**Comment by vanniktech** [comment]
I still don't know what you're doing or why you have your own EmojiTextView class. Can you reproduce in the sample app? If not, there's an issue on your side.

**Comment by runner26** [comment]
Ty for your reply, I am tasked to solve the emoji issues and I am not the actual developer of this app. So you are saying that the EmojiTextView is wrong? I will try using your default  EmojiTextView.

**Comment by vanniktech** [comment]
> Ty for your reply, I am tasked to solve the emoji issues and I am not the actual developer of this app.

So it seems like it's a problem on your side. Hence I'm closing this. Feel free to play around with the sample app included in the repository (this one is working to my knowledge).

**Comment by Mr-Ramzan** [comment]
> Ty for your reply, I am tasked to solve the emoji issues and I am not the actual developer of this app. So you are saying that the EmojiTextView is wrong? I will try using your default EmojiTextView.

were you able to solve the issue,  please  share the solution
