### ISSUE TITLE
Some emojis are missing

### ISSUE THREAD

**Issue by snowf0x** [vanniktech/Emoji#301]
Hello, I am new to github, I dont know if it the right place to post it but,

On using emojis, some particular emojis are missing even though it's present in this repo like,

https://github.com/vanniktech/Emoji/blob/master/emoji-twitter/src/main/res/drawable-nodpi/emoji_twitter_sheet_38.png

here,
![capture](https://user-images.githubusercontent.com/41299873/45594840-09da6580-b9bf-11e8-97ab-53919eb00248.PNG)
these emojis are not available inside my app
![screenshot_20180916-144605](https://user-images.githubusercontent.com/41299873/45594882-b0266b00-b9bf-11e8-85fc-8b7fbe89f1a0.png)

**Comment by runner26** [comment]
I waited 2 days already not news

**Comment by runner26** [comment]
At least you still can get some I totally not able to receive any emoji at all. I have waited 2 days and I can't launch my app BECAUSE I am stuck in this one
![screenshot_2018-09-15-08-57-54-409_biz hashtag chat](https://user-images.githubusercontent.com/36129895/45595500-88df9600-b9df-11e8-89a8-7d37ceae0f63.png)

**Comment by snowf0x** [comment]
Actually my solution would me as simple as adding (hope so)

new TwitterEmoji(0x1F929, 38, 50)

in

https://github.com/vanniktech/Emoji/blob/master/emoji-twitter/src/main/java/com/vanniktech/emoji/twitter/category/SmileysAndPeopleCategory.java

**Comment by vanniktech** [comment]
@snowf0x can you test out `0.6.0-SNAPSHOT`? There have been quite a few changes and it's likely that this is already fixed.

**Comment by snowf0x** [comment]
Working as a charm! Thankyou for this, and this awesome project!
