### ISSUE TITLE
does not work error when opened

### ISSUE THREAD

**Issue by djbenbe** [vanniktech/Emoji#304]
it does not work for me. or am I doing something wrong?
I open the emoji and I get this error on my laptop

![image](https://user-images.githubusercontent.com/12442307/46259606-e85b9c80-c4db-11e8-932c-f8915e17cb31.png)

**Comment by vanniktech** [comment]
Which provider and which version are you using?

**Comment by djbenbe** [comment]
android 8 and 7
0.5.2

**Comment by vanniktech** [comment]
Does the sample app work for you? If that's the case there's something wrong on your end.

**Comment by djbenbe** [comment]
where is he?

**Comment by vanniktech** [comment]
Should not matter. Tested out the sample locally and this one works so there's something wrong on your side.

**Comment by djbenbe** [comment]
> Zou er niet toe doen. Testte het monster lokaal en deze werkt, dus er is iets mis aan jouw zijde.

you do not use kotlin. it is therefore that I can not compare with you
