### ISSUE TITLE
do not open emoji. he also blocks with test app

### ISSUE THREAD

**Issue by djbenbe** [vanniktech/Emoji#305]
with the test app it also does not work on my smartphone hear with my app get the same error.

samsung galaxy s9 =  android 8
samsung galaxy a5 = android 7

**Comment by vanniktech** [comment]
This is not actionable. You're not providing any information.

**Comment by djbenbe** [comment]
same mistake with what you have closed too quickly

**Comment by djbenbe** [comment]
![image](https://user-images.githubusercontent.com/12442307/46293937-f6212880-c594-11e8-81fa-0cf8f01072a8.png)
![image](https://user-images.githubusercontent.com/12442307/46294008-1ea92280-c595-11e8-9fcf-634ad5ea51bf.png)

**Comment by vanniktech** [comment]
This is not the sample app and there are no steps on how to reproduce your problem or even a description of what is actually wrong. Also, feel free to use this library but I won't provide any help with implementing it. The sample app is working on my set up.
