### ISSUE TITLE
with sdkversion 28 doesnt work

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#307]
with sdkversion 28
implementation 'androidx.appcompat:appcompat:1.0.0'
EdiText is not compatible with EmojiEditText

**Comment by vanniktech** [comment]
Yeah I don't think we're Android x compatible. Can't you use jetifier?

**Comment by hvar90** [comment]
how  can i use that ? 
i have 
android.useAndroidX=true

android.enableJetifier=true
but i dont know how to use that to resolve my problem

**Comment by hvar90** [comment]
the problem is, incompatible types
EmojiEditText is not reconigzed as a EdiText
so i can not use the methods of EdiText with EmojiEditText

**Comment by vanniktech** [comment]
Can you try out the 0.6.0-SNAPSHOT? I think I updated to targetSdk 28 there.

**Comment by vanniktech** [comment]
Also, I think the library is doing everything and correct and if so there's a bug in Jetifier. At some point, I'll migrate this to be using the androidx releases though or someone does it for me.

**Comment by hvar90** [comment]
yes, with  0.6.0-SNAPSHOT works well
thanks ...
