### ISSUE TITLE
emojiPopup.toggle(); not working when the device is in landscape mode

### ISSUE THREAD

**Issue by Noddy20** [vanniktech/Emoji#314]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
That can indeed be the case. Happy to take a PR that fixes this.

**Comment by rubengees** [comment]
As a workaround in the meantime, you can set

```
android:imeOptions="flagNoExtractUi"
```

on your `EmojiEditText`.

**Comment by Noddy20** [comment]
It worked :) @rocboronat 
Thnx @rubengees & @vanniktech 👍

**Comment by vanniktech** [comment]
Thanks for the workaround @rubengees
