### ISSUE TITLE
Converting String unicode to hex integer

### ISSUE THREAD

**Issue by premacck** [vanniktech/Emoji#317]
Hey @vanniktech 
I am running 0.5.1 version of this library in my project.
Is there any way to convert the string unicode, that is obtained in the unicode field of the imageView parameter of onEmojiClick() method in OnEmojiClickListener, to hex integer?

I have tried
Integer.parseInt(unicode)
Integer.parseInt(unicode.subString(2)) - to remove the 'U+' from first
I've also tried [this](https://stackoverflow.com/a/36729509) answer on stackOverflow.

But evey time it is giving me NumberFormatException. Any help will be greatly appreciated

**Comment by vanniktech** [comment]
Nope. Why would you want to do this?
