### ISSUE TITLE
Question about EmojiTextView parsing shortcodes of emoji(:smile:), not unicode.

### ISSUE THREAD

**Issue by tokkerbaz** [vanniktech/Emoji#318]
Hi, my question is **"Is there such possibility to parse codes of emojis in EmojiTextView"?**
Like in the link below.
[https://www.webpagefx.com/tools/emoji-cheat-sheet/](https://www.webpagefx.com/tools/emoji-cheat-sheet/)

In example, i have text like this: `"Hi,how are you doing?:relaxed:"`.  Text is using codes instead of unicode.

And also want to thank you for the very usefull lib.

- Version of the library: 'com.vanniktech:emoji-ios:0.5.1'

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Nope, not yet. @rubengees wanted to start this by parsing the codes and providing an API for getting aliases for each emoji. Dunno what the state is. Feel free to tinker around with the generator.

**Comment by tokkerbaz** [comment]
Thank you, for now may be will close this issue

**Comment by rubengees** [comment]
I had this ready on a branch I think, I'll look into what the state of that was exactly.
Simply replacing shortcodes with emojis would not be that hard I think, but showing suggestions when the user was typing was, so I never finished that.
The former could be implemented by having a property on the `Emoji*View` to allow for that and simply adding the aliases to the regex used for finding the right emoji drawable.
