### ISSUE TITLE
emojiPopup.toggle(); not working in DialogActivity and Dual WIndow Mode

### ISSUE THREAD

**Issue by Noddy20** [vanniktech/Emoji#321]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by Noddy20** [comment]
In DialogActivity it works only when the phone is in landscape mode. 
And not working in Dual Window mode (i'm using LG device's dual window feature).
Thank you.

**Comment by vanniktech** [comment]
Yeah, that could be the case. As far as I know, we don't do special window handling. Mind cracking out a fix? I won't have the time to investigate this further.

**Comment by Noddy20** [comment]
ok
