### ISSUE TITLE
Weird behaviour in landscape when flagNoExtractUi is not set

### ISSUE THREAD

**Issue by rubengees** [vanniktech/Emoji#328]
- Version of the library: 748c208
- Affected devices: All
- Affected versions: All

When opening the emoji keyboard in landscape, the emoji picker is shown on it's own, without the `EditText`. I reproduced that on a default API 28 emulator.
Setting `android:imeOptions="flagNoExtractUi"` works around like before. 

![](https://user-images.githubusercontent.com/8021265/51638587-05bae780-1f5f-11e9-9ef5-3b132b3fe236.png)

@mario I think that is related to your change?

**Comment by mario** [comment]
On it already.

**Comment by mario** [comment]
I'd like to be able to push branches to this repo so I don't have to keep my fork if it's not too much trouble.

Got a fix for this problem btw, and a few other related problems.

**Comment by mario** [comment]
Ignore me, I can. It's just too late :-/
