### ISSUE TITLE
Add licencing header to every file

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#331]
Due to legal reasons, it is recommended to add licencing header to every file that includes contributors to the file, year, and the gist of the licence (in this case APL).

**Comment by vanniktech** [comment]
The only thing that worries me is the year. What should we put there?

**Comment by mario** [comment]
Well, usually you put in the whole copyright range. But if you create a new file today, you can put just 2019.

**Comment by vanniktech** [comment]
Can we take the year where the current file was first created?

**Comment by vanniktech** [comment]
Then let's do it just like RxJava does it and also apply it to each file. In the file, we use the date that the file was first seen in the repo. With this, we should be fine.

**Comment by vanniktech** [comment]
Let's get this into 0.6.0 as well.

**Comment by mario** [comment]
Unlikely due to my time constraints, unless you can do it @vanniktech.

**Comment by vanniktech** [comment]
Nah I'm not eager for it :D

**Comment by mario** [comment]
Slacker :p
