### ISSUE TITLE
Skin tones support

### ISSUE THREAD

**Issue by rafaelekol** [vanniktech/Emoji#34]
I can help you with adding skin tones. Do you have ideas how to map them? Since skin toned emoji has two unicode characters (0x1f4aa 0x1f3fb) I am not sure how it can be handled.

EMOJIS_MAP.put(0x1f4aa, R.drawable.emoji_1f4aa_1f3fb);

**Comment by vanniktech** [comment]
Yup this is also missing. Nope so far now idea on how to map them. Haven't gotten the time to read around this.

All I know is that they have a skin 'modifier'. Also there are 6 different ones. Some information can be found [http://unicode.org/reports/tr51/](here). They have a list of the modifiers and also go into detail.

**Comment by rafaelekol** [comment]
In EmojiHandler I used this code to get emoji drawable via dynamic name generated from found unicode. This way we don't need to use SparseArray filled with emoji id linked to their unicodes. And this way dealing with skin codes is much easier.

```
String emojiName = "";

                if (unicode > 0xff) {
                    String hex = Integer.toString(unicode, 16);
                    emojiName = "emoji_" + hex;

                    int emojiId = App.getContext().getResources().getIdentifier(emojiName, "drawable", App.getContext().getPackageName());
                    icon = emojiId;
                }

                if (i + skip < textLength) {
                    final int followUnicode = Character.codePointAt(text, i + skip);

                    //handle skin toned emojis
                    if (!TextUtils.isEmpty(emojiName) && followUnicode >= 0x1f3fb && followUnicode <=0x1f3ff) {
                        String hex = Integer.toString(followUnicode, 16);
                        emojiName = emojiName + "_" + hex;
                        int emojiId = App.getContext().getResources().getIdentifier(emojiName, "drawable", App.getContext().getPackageName());
                        if (emojiId > 0) {
                            icon = emojiId;
                            int followSkip = Character.charCount(followUnicode);
                            skip += followSkip;
                        }
                        Log.d(TAG, "addEmojis skincode: " + hex);
                    }
}
```

**Comment by vanniktech** [comment]
True it is easier though using reflection for doing that is super expensive. I'd prefer to have this huge dynamic array. As far as I know they get their skin modifier just appended at the end right? So `0x1f60d` bekomes `0x1f60d_6749` where `6749` would be the skin modifier, right?

**Comment by vanniktech** [comment]
Viewing is supported. Editing from the emoji keyboard not yet although that one is tracked as #80
