### ISSUE TITLE
Other UI elements can't be selected when emoji popup is visible

### ISSUE THREAD

**Issue by rubengees** [vanniktech/Emoji#340]
- Version of the library: Latest `master`
- Affected devices: All
- Affected versions: All

When selecting another UI element while the popup is visible, the popup is first closed and another click is required to trigger the UI element.

This is due to this line, introduced in https://github.com/vanniktech/Emoji/pull/333:

https://github.com/vanniktech/Emoji/blob/985af973137a8224c1a945f22fa6d33b6d1b118e/emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java#L168

I guess we should revert that @mario @vanniktech?

**Comment by mario** [comment]
This has to be there, otherwise the back button doesn't function properly? :) E.g. it wouldn't close the popup window.

**Comment by rubengees** [comment]
I disagree, as a user I would expect the back button to close the keyboard, if it is the emoji one or the normal one. This is also the behaviour of all apps I know of (WhatsApp, Telegram, Slack, ...). Before the change, that was also the behaviour of this lib.

**Comment by mario** [comment]
Well, exactly. If you remove this, the regular keyboard is dismissed BEFORE the emoji keyboard. At least that was my experience.

**Comment by rubengees** [comment]
Ah, I see! Can't reproduce that on my emulator (after removing the line in question), but if that happens on specific devices it's a bug we need to fix in a different way. The behaviour now is counterintuitive for the user and in conflict with the behaviour of most (all I know) other apps.

**Comment by mario** [comment]
I can take a look after I've hunted down the previous bug you found.

**Comment by rubengees** [comment]
Great, thanks! :+1:

**Comment by vanniktech** [comment]
Awesome. Thanks for figuring this out!

**Comment by vanniktech** [comment]
@mario this can also be closed now, right?

**Comment by mario** [comment]
Yes @vanniktech, this has also been fixed via #329.
