### ISSUE TITLE
Can you tell me how to show Emojis in Action Bar Title?

### ISSUE THREAD

**Issue by EbelloImbox** [vanniktech/Emoji#341]
Hello, I am using 0.5.1 version and I would like to know how to change Action Bar title to show your Emojis.

Like you can see in the following pictures, Emojis is not showing correctly, because I am using Google Emojis and I can see it in all my app replacing TextView by your, but I can not change the TextView in Action Bars.

Cheers.

![image](https://user-images.githubusercontent.com/46479160/52705713-e32b5580-2f83-11e9-9b0d-f1d8798ba283.png)

I am not using any kind of custom Emojis, I am using only Google Emojis:
![image](https://user-images.githubusercontent.com/46479160/52705808-1bcb2f00-2f84-11e9-8971-ee6680411c1c.png)

EDIT: I am using an Action Bar and SDK 26 to compile and I can not use a Tootbar (the art of legacy code).

**Comment by vanniktech** [comment]
Custom tab bar with our EmojiTextView or handle it yourself.

**Comment by mario** [comment]
I'll add this eventually, it's relatively trivial since I've already done it.

**Comment by mario** [comment]
We're tracking the issue here: https://github.com/vanniktech/Emoji/issues/342

**Comment by EbelloImbox** [comment]
For people that are experimenting problem like this, you can solve it with a Custom ActionBar like this:

Java:
`
final ActionBar actionBar = this.getSupportActionBar();
actionBar.setDisplayOptions(ActionBar.DISPLAY_SHOW_CUSTOM);
actionBar.setDisplayShowCustomEnabled(true);

View v = getLayoutInflater().inflate(R.layout.titleview, null);
titleActionBar = v.findViewById(R.id.title);

actionBar.setCustomView(v);`

XML:
`
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/transparent" >

    <com.vanniktech.emoji.EmojiTextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:textSize="20sp"
        android:textColor="@android:color/white"
        android:maxLines="1"
        android:ellipsize="end"
        android:text="Test" />
</RelativeLayout>`
