### ISSUE TITLE
Add EmojiActionBar

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#342]

**Comment by vanniktech** [comment]
I'll cut a new release soon. Do you want to include this @mario ?

**Comment by mario** [comment]
Dunno, working on other things for the library atm :)

**Comment by vanniktech** [comment]
Can you copy paste the code you have into this issue? I need this in a project of mine with `com.google.android.material.appbar.MaterialToolbar`

**Comment by mario** [comment]
Closing in favour of a layout factory.
