### ISSUE TITLE
Discuss repo/naming changes if GIF support is added

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#343]
So I plan to add a GIF support eventually. Would we change the repo name and the classes if this happens?

In addition, is any one of you willing to lend a hand here or are you simply too busy? :-/

**Comment by vanniktech** [comment]
Unfortunately, I won't be able to help out. What would the new name be?

**Comment by mario** [comment]
Didn't think about it yet, but if it supports more than Emoji than Emoji might not be a fit anymore :)

What do you @rubengees thinks? Also, are you available for pairing up on this?

**Comment by rubengees** [comment]
Hmm, no great name comes to mind yet. But I think "keyboard" should be included, since that is what this library mainly does.

Depends on how busy work is and how motivated I am ;) But I can imagine to help out here and there, even though that would not be a feature, I actively need.

**Comment by vanniktech** [comment]
EmojiGifKeyboard?

**Comment by mario** [comment]
While that would clearly explain the functionality, is it too generic?

**Comment by vanniktech** [comment]
Dunno. I was thinking we could provide one module that has a basic keyboard pluggable mechanism and then you can plug in different features. Like Emojis. Gifs. Stickers. Whatever you want / need.

**Comment by mario** [comment]
This is what I would do, yes.

**Comment by vanniktech** [comment]
How about just `Keyboard`?

Also, do we need to leave this issue open?

**Comment by mario** [comment]
Nah, close it and we'll discuss more when we come to it :)
