### ISSUE TITLE
Add facebook and whatsapp emojis

### ISSUE THREAD

**Issue by Asimkhanmak** [vanniktech/Emoji#344]
Please add facebook and whatsapp emojis too.
Thanks

----------------------------------------------------------------------

**Comment by mario** [comment]
WhatsApp is highly unlikely as our upstream emoji source data doesn't support it, and while we might consider Facebook/Messenger, it is very likely that it'll come if someone contributes.

If you have any questions on how to do that once you get around to looking at the generator source code, we'll be happy to answer them!

**Comment by rubengees** [comment]
Facebook would be easy to add, I'll look at it once I have time.

**Comment by vanniktech** [comment]
Whatsapp are using iOS emojis, no?

**Comment by rubengees** [comment]
No, they have their own since some time ago.

**Comment by vanniktech** [comment]
Oh interesting. Didn't notice. (Haven't forgotten the release - just super busy at work)

**Comment by vanniktech** [comment]
We can start doing this right? I think they updated their sources @rubengees

**Comment by rubengees** [comment]
Yes, will look soon at updating :+1:
