### ISSUE TITLE
Problems with version 0.6.0 and SDK 26

### ISSUE THREAD

**Issue by EbelloImbox** [vanniktech/Emoji#345]
Hello, I am using version 0.5.1 of this library and I want to update to 0.6.0, but I am using to compile SDK 26 and I can not upload it right now.

Are there any way to use the version 0.6.0 with SDK 26? This is the error that show me:

![image](https://user-images.githubusercontent.com/46479160/52949168-ca53e300-337b-11e9-8345-edc6ca6fcde8.png)

**Comment by vanniktech** [comment]
Yeah. Time to update to 28.0.0 or downgrade your version using Gradle's resolutionStrategy.
