### ISSUE TITLE
 Emoji library issue with accessibility

### ISSUE THREAD

**Issue by AlexMavDev** [vanniktech/Emoji#348]
- Version of the library: com.vanniktech:emoji-google:0.6.0
- Affected devices: All devices
- Affected versions: Most recent

Reproduction steps
1) Turn on talkback following these steps:
Settings (app) > Accessibility (list option) > Talkback (list option) > Switch ON
2) Navigate until any point where the Emoji popup is used and open it.
3) Select any emoji from a category. 
4) Talkback announces 'Unlabeled button'. The expected behavior is to announce the respective emoji e.g. 'Smiling face ...' 

If you select the EmojiEditText associated to the EmojiPopup and it contains an emoji, Talkback announces the emoji correctly.

You can include support to Accessibility for Talkback adding the below code line in the getView method of the EmojiArrayAdapter class:

image.setContentDescription(emoji.getUnicode());

Similar line needs to be added in the respective adapter for the category tabs.

----------------------------------------------------------------------

**Comment by rubengees** [comment]
Would you like to do a pull request for that? Otherwise I or @mario, @vanniktech will eventuelly come to it.

**Comment by AlexMavDev** [comment]
Sure

**Comment by AlexMavDev** [comment]
Hi guys,
I've done all the appropriate changes in the library. Do you need to assign me permission for doing the push?

**Comment by mario** [comment]
Could you push to your fork and open a PR then, please?

**Comment by AlexMavDev** [comment]
Yeah,
https://github.com/vanniktech/Emoji/pull/352

**Comment by mario** [comment]
Closing since the PR was merged, thanks for this @AlexMavDev.

**Comment by scalajay** [comment]
Hi all, can we get a new release? Im really looking forward to using this accessibility patch. Thank you.
