### ISSUE TITLE
Some emojis small size (wrong size)

### ISSUE THREAD

**Issue by Sulfkain** [vanniktech/Emoji#349]
Hello,
I'm using the TwitterEmoji and lib version v0.5.1, and everything works perfect.

But now, we are migrating to the iOS emojis, and lib v0.6.0.
The problem is, some emojis are resized to the min size (no clue why some works, others no)
If I change the icon (wrong resize) to the iOS version using the last lib with iOS emojis.
Then it will show it perfect on new version with iOS or in 0.5.1 with TwitterEmoji version.

Looking at https://unicode.org/emoji/charts/full-emoji-list.html we are seeing some problem could appear by "detective" vs "man detective".
But other are weird, because are just one "clamp"

My view is this, the same on old version and new version
```
        <com.vanniktech.emoji.EmojiTextView
            android:id="@+id/userEmoji"
            android:layout_width="@dimen/emoji_text_size" -> 60dp
            android:layout_height="@dimen/emoji_text_size"
            android:gravity="center"
            android:minHeight="@dimen/emoji_size"
            android:minWidth="@dimen/emoji_size" -> 44dp
            app:emojiSize="@dimen/emoji_size"
            app:layout_constrainedHeight="true"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintDimensionRatio="1:1"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tool:text="🤗" />
```

I have tried the README tip with `lineHeight` but it doesn't change anything even on a new brand and no extra params EmojiTextView on other layout.

As extra point, the emojis with this result on some blurry icons by the resize, while on the old version with Twitter (maybe because are much plain) doesn't appear to be blurry.

Thank's for this great lib!.

![emojiissue](https://user-images.githubusercontent.com/17082246/53746973-8fd16680-3ea2-11e9-9412-5d6ddf8a4364.jpg)

**Comment by vanniktech** [comment]
@rubengees is our data source pulling the images in different sizes?

**Comment by rubengees** [comment]
@vanniktech No, as far as I know. Not sure what causes this...

**Comment by mario** [comment]
Can I ask why is EmojiTextView used for this anyway? For your usecase EmojiImageView looks better...

**Comment by Sulfkain** [comment]
@mario I even know this class exists, no doc on README about it. Could be a great time to add it
And on v0.5.1 didn't exist that class.

I have tried to implement it, but no doc available about how to use. Or test to show how to use it.
So I was reading code and trying to understand it.
The only public method is `updateEmoji` but says on code doc, it will only be use to update to the same emoji base (I suposse tone skin for ex. no?).

And another problem even if i could use `setEmoji` (which is internal and not visible) is how I can get a Emoji object from a emoji text?
Because when I get data from server I only get a String with the emoji, not an emoji object.

Thank you.

**Comment by vanniktech** [comment]
Closing in favor of #354

Feel free to add some documentation to the README!

**Comment by Sulfkain** [comment]
@vanniktech The problem as I told on the message is I even know how to use it.
And I'm asking for help or documentation.

Thanks to open your proyect to contribution, but I need first help and later I could add some doc based on my little experience.
But please, help me first with some info about that classes and resolve my questions.

Thank's

**Comment by vanniktech** [comment]
Look at the class. It's rather straight forward what it does and it should be obvious how to use it :)

**Comment by Sulfkain** [comment]
Sorry but it doesn't, as I told, I already readed` EmojiImageView` and try to implement but it not really easy to use.
Could you please answer my questions?

> The only public method is updateEmoji but it says on code doc, it will only be use to update to the same emoji base (I suposse tone skin for ex. no?).
> And another problem even if i could use setEmoji (which is internal and not visible) is how I can get a Emoji object from a emoji text?
> Because when I get data from server I only get a String with the emoji, not an emoji object.

Thanks.

**Comment by vanniktech** [comment]
I won't. I don't have the time neither do I have the resources to answer questions. I'm maintaining this in my free time and will allocate the time that I spend on such projects on my schedule. 

Maybe someone else will answer your question. You can also try stackoverflow.

**Comment by Sulfkain** [comment]
Ok, thanks.
@mario could you throw more info about that class and if you could resolve the questions will be really apreciate.

Thanks
