### ISSUE TITLE
Show 4 emojis if I send a family Emoji in a iOS device

### ISSUE THREAD

**Issue by EbelloImbox** [vanniktech/Emoji#350]
Hello to everyone, first of all, I would like to tell you that I appreciate too much your work.

Well, my problem (or question) is when I send an Emoji like this:

![image](https://user-images.githubusercontent.com/46479160/53799206-2c931300-3f3a-11e9-88b9-ae91a01d55fd.png)

and I receive it in my Android app with this library everything works fine, but if I send this Emoji to an iOS device (that use the native system Emoji) shows 4 Emojis.

If I debug my app and I get the text from my EmojiEditText when I send this Emoji, I can see that the text is formed by 4 Emojis:

![image](https://user-images.githubusercontent.com/46479160/53799561-ed18f680-3f3a-11e9-8239-6749bfde401a.png)

Do you have any idea of how to manage it?

Version: 'com.vanniktech:emoji-ios:0.5.1'

**Comment by vanniktech** [comment]
Those emojis are actually composed of those 4 unicode's one so this is working as intended.

**Comment by EbelloImbox** [comment]
Thank you for your quickly answer.

Do you have any idea about how to get that iOS people can see correctly this Emojis?

**Comment by mario** [comment]
The question is how you store this in the database and then what you set to the TextView - on the Android side it's CharSequence. I just tested this on an iOS app that we're working on, and this works as expected so has nothing to do with the lib :)

Let us know if we can assist in any other way!
