### ISSUE TITLE
How to integrate into actual softkeyboard.

### ISSUE THREAD

**Issue by dangerchitthu** [vanniktech/Emoji#355]
Pls Help Me......
Does anyone knows how to integrate this project into the actual softkeyboard? I mean not the stock keyboard (AOSP), but the custom softkeyboard sample provided in the legacy android sdk.

**Comment by vanniktech** [comment]
No and I don't think we want to have this.

**Comment by dangerchitthu** [comment]
h
![Screenshot_1555473645](https://user-images.githubusercontent.com/12719655/56260326-d40c7500-60a4-11e9-953b-549980696292.png)
