### ISSUE TITLE
Rectangle Emoji Size

### ISSUE THREAD

**Issue by omkar1707** [vanniktech/Emoji#357]
I am using this library to load my custom emojis. 
My emoji size is not square. Each emoji is a rectangle in shape Eg. 64X80.

When I click on emoji and send it. The EmojiEditText shows the emoji bit stretched.  
PFA screenshot for the same.

How I can modify to the code to make it look not stretched?

![Screenshot_1555570537](https://user-images.githubusercontent.com/26362645/56342432-a6731900-61d5-11e9-8f7e-d6fece882a11.png)

**Comment by vanniktech** [comment]
> My emoji size is not square. Each emoji is a rectangle in shape Eg. 64X80.

Yeah, that's what happens when you use rectangles. Try using fitCenter

**Comment by omkar1707** [comment]
@vanniktech Where should I use the fit center? Can you point it out?
