### ISSUE TITLE
Emoji is not shown correct

### ISSUE THREAD

**Issue by puneethkumar450** [vanniktech/Emoji#358]
----------------------------------------------------------------------

🙋‍♂️ (man raising hand)
 it shows separately with boy gender
![34350316-3806b140-ea51-11e7-98b8-0e4a6ecc613c](https://user-images.githubusercontent.com/17966527/56431897-1e7e3380-62e9-11e9-8b95-d6e7a9f012d5.png)

check the link it shows separately.

the same way the family is shown separately with the boy , girl , father, mother

**Comment by puneethkumar450** [comment]
Can you please help me with this

**Comment by rubengees** [comment]
Can you test the latest commit from master? It might be fixed there: https://github.com/vanniktech/Emoji#snapshots

**Comment by puneethkumar450** [comment]
Ya, It's working Fine.

Why can't you open EMOJI KEYBOARD without opening soft keyboard

**Comment by vanniktech** [comment]
Because we need the soft keyboard to calculate the proper height.

**Comment by puneethkumar450** [comment]
I think Keyboard size will be the default for all the mobiles.
