### ISSUE TITLE
How to add customize emoji by String not integar!

### ISSUE THREAD

**Issue by omar-othmann** [vanniktech/Emoji#359]
Hello, how i can add custom emoji by String like:

INSTANCE.emojiMap.put("@}->--", new IosEmoji(0x1F339, 6, 47));
INSTANCE.emojiMap.put(":D", new IosEmoji(0x1F339, 6, 47));
etc.....

Thank you

**Comment by vanniktech** [comment]
Provide your own Category with a custom Emjoi instance that contains the Unicode instances.
