### ISSUE TITLE
EmojiPopUp without editText

### ISSUE THREAD

**Issue by Hosseinyzr** [vanniktech/Emoji#363]
Hello,thanks for this  ripo.
I just wnat to show the emojipopup and when click on some emoji , set the emoji to according emojitextview.
I don't need any edittext ,but as I found, I should provide one. any idea?

**Comment by Hosseinyzr** [comment]
And is there any feature like emojiDialog? just for selecting one emoji from it...

**Comment by vanniktech** [comment]
Not yet.
