### ISSUE TITLE
Request to update Google emoji

### ISSUE THREAD

**Issue by tcqq** [vanniktech/Emoji#364]
@vanniktech Request to update the latest Google [emoji](https://emojipedia.org/google/).
![image](https://user-images.githubusercontent.com/10644057/58608460-3bd5f280-82d6-11e9-9029-fa77f3b19585.png)

**Comment by vanniktech** [comment]
Feel free to submit a PR.

**Comment by m3toh** [comment]
@vanniktech can you update ios emoji please :blush:

**Comment by vanniktech** [comment]
Will be part of #356
