### ISSUE TITLE
Adding toggle mode with a specific height.

### ISSUE THREAD

**Issue by VitalyKuznetsov** [vanniktech/Emoji#372]
Hi!

Would it be possible to add a different open mode to the library, that would allow for EmojiPopup to be opened without opening the keyboard first.
Something like ```open(int height)```.
I would be much happier to use such method instead of the current one.

Thanks in advance!

**Comment by vanniktech** [comment]
Why? How would you get the height of keyboard?

**Comment by VitalyKuznetsov** [comment]
Some apps may listen for the first keyboard opening event and store keyboard height value until the height is changed by the user (think telegram, whatsapp etc.)
Such use case can also be applied to the application I am working on. There already exists a View that replaces the keyboard and saves its height. I would like to add your library to my project but to continue to use it in the same workflow I currently have.
However current library API doesn't allow for such manipulation. It is great for the "out of the box" use and without saving the height of keyboard, but not in the aforementioned scenario.
I am thinking such addition will improve the library and make it easier to use for applications like mine.
If such behavior option is desirable then I will be happy to contribute a PR of my own.

**Comment by vanniktech** [comment]
That makes sense. We could add the `height` to the Builder and don't calculate it our self if it's provided.

**Comment by VitalyKuznetsov** [comment]
Here goes - https://github.com/vanniktech/Emoji/pull/373

**Comment by VitalyKuznetsov** [comment]
Hey again!
I answered the review comment in the PR, but there was no update ever since...

**Comment by vanniktech** [comment]
This is supported now #373
