### ISSUE TITLE
opening keyboard and emoji in the same time!

### ISSUE THREAD

**Issue by bagvand** [vanniktech/Emoji#375]
Hello
Device: Galaxy A7 20116.
ModelNumber: SM-A710FD

![Screenshot_20190908-132529](https://user-images.githubusercontent.com/3761338/64486023-2198a280-d23d-11e9-8e22-22231f5192f0.png)

Thnx.

**Comment by vanniktech** [comment]
Which device is that? https://github.com/vanniktech/Emoji/pull/346 might fix this

**Comment by bagvand** [comment]
Device: Galaxy A7 20116.
after merge this #346 the emoji keyboard will be gone.
![Screenshot_20190915-155331](https://user-images.githubusercontent.com/3761338/64920905-dd277c80-d7d1-11e9-8fd5-49c7cd707c18.png)

**Comment by vanniktech** [comment]
Gone meaning it's fixed or there are still problems?

**Comment by bagvand** [comment]
No problem exists. Emoji keyboard has gone forever!

**Comment by vanniktech** [comment]
Good that we haven't merged this yet

**Comment by vanniktech** [comment]
@bagvand do you mind trying #386 ?

**Comment by mario** [comment]
This is considered fixed. If it happens again, please re-open.

**Comment by bagvand** [comment]
@vanniktech @mario 
After using the last commit of branch master, our problem of keyboard and emoji keyboard becomes worst.
the number of users that are unsatisfied becomes bigger.
