### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by mehranj73** [vanniktech/Emoji#381]
I'm really sorry for my question. I'm having trouble setting this up, maybe I'm just stupid. Can anyone provide me a simple example? Please I really need this. Thank you

**Comment by rubengees** [comment]
What do you have and what is the problem/error?

**Comment by mehranj73** [comment]
What is 'Don't use bundled AppCompat emojis. Instead download the font' mean? and I can't find dependency for GoogleCompatEmojiProvider.

**Comment by vanniktech** [comment]
This is a commit.

**Comment by vanniktech** [comment]
`GoogleCompatEmojiProvider` is inside the google compat library module.

**Comment by mehranj73** [comment]
I'm using androidx and I couldn't fix my problem.

**Comment by vanniktech** [comment]
So are we.

**Comment by mehranj73** [comment]
What is this error?
Unable to start activity ComponentInfo{com.vanniktech.tryingkeyboard/com.vanniktech.tryingkeyboard.MainActivity}: android.view.InflateException: Binary XML file line #10 in com.vanniktech.tryingkeyboard:layout/activity_main: Binary XML file line #10 in com.vanniktech.tryingkeyboard:layout/activity_main: Error inflating class com.vanniktech.emoji.EmojiEditText

**Comment by mehranj73** [comment]
I fixed it by using like this:
       EmojiManager.install(new IosEmojiProvider());
        setContentView(R.layout.activity_main);

**Comment by vanniktech** [comment]
You're saying you followed the readme?

```
// This line needs to be executed before any usage of EmojiTextView, EmojiEditText or EmojiButton.
EmojiManager.install(new IosEmojiProvider());
```
