### ISSUE TITLE
Emoji keyboard open doesn't trigger real keyboard

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#384]
Steps:

1) Launch emoji keyboard
2) Close it
3) Launch if again and see that there's no real keyboard behind

**Comment by vanniktech** [comment]
Was this after #378 or #373 ?

**Comment by mario** [comment]
#373 as far as I know for now. Working on it.

**Comment by mario** [comment]
Fixed via https://github.com/vanniktech/Emoji/pull/389

**Comment by vanniktech** [comment]
Thanks! Currently, blocked by the issue @rubengees found.

**Comment by mario** [comment]
Fixed so closing.
