### ISSUE TITLE
Emoji & keyboard shown when user click home(back) button in appbar

### ISSUE THREAD

**Issue by e-erbolat** [vanniktech/Emoji#387]
I use emoji ios, when keyboard opened and shown emoji keyboard, user click home(back) button in appbar, after that automatically shown keyboard & emoji keyboard.

- Version of the library: emoji-ios:0.6.0
- Affected devices: LGE LG-K200 
- Affected versions: 6.1 (os)

Screenshot: http://prnt.sc/part5g
Video: https://gofile.io/?c=8spjz9

----------------------------------------------------------------------

**Comment by rubengees** [comment]
Duplicate of this: https://github.com/vanniktech/Emoji/issues/375
