### ISSUE TITLE
Soft keyboard under emoji keyboard

### ISSUE THREAD

**Issue by mehranj73** [vanniktech/Emoji#388]
Hey, I built this simple app. When I touch the emoji button to activate emoji keyboard, the soft keyboard appears under it for a second and it kinda makes it ugly. I compared it Telegram's emoji keyboard which is really smooth. 
![a](https://user-images.githubusercontent.com/41204086/65803594-dc0c2d00-e18b-11e9-9aed-e46e854eb4a2.gif)
![b](https://user-images.githubusercontent.com/41204086/65803657-1249ac80-e18c-11e9-97dc-c9d5ec0906c0.gif)

**Comment by mehranj73** [comment]
Why the soft keyboard is activated when I just want the emoji keyboard?

**Comment by vanniktech** [comment]
There's a method for this in the SNAPSHOT.

```
editText.disableKeyboardInput(emojiPopup)
```

**Comment by mehranj73** [comment]
It means that it is going to be added in the future stable updates? because I can wait.

**Comment by vanniktech** [comment]
Yup

**Comment by vanniktech** [comment]
Will close this and it'll be in 0.7.0 which I'll cut soon-ish

**Comment by mehranj73** [comment]
nice
