### ISSUE TITLE
can't add "com.vanniktech:emoji" library to my project

### ISSUE THREAD

**Issue by chiragakbari** [vanniktech/Emoji#40]
i got an emoji library from here [https://github.com/vanniktech/Emoji](url)

i am trying to add emoji library to my android project but when i compile below line it gives me error which is shown in screen shot.

if anyone use this library and getting same then please help.

Thanks in advance.

compile 'com.vanniktech:emoji:0.4.0'
compile 'com.vanniktech:emoji:0.4.0-SNAPSHOT

my android studio version is 2.1.2

![error](https://cloud.githubusercontent.com/assets/19163596/16263079/15081572-3890-11e6-84c7-41a8bdb1dc78.png)

**Comment by vanniktech** [comment]
You need `compile 'com.vanniktech:emoji:0.3.0'`.

Version `0.4.0` is not released yet. If you want the SNAPSHOT you have to add this:

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by chiragakbari** [comment]
Thanks for your reply.

it works now. thank you once again.
