### ISSUE TITLE
Rip-off?

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#404]
This library looks like a serious rip-off of what we're working on here.

https://github.com/TutorialsAndroid/SEmojis/tree/master/semojis

While it's not a straight copy & paste at most places, the inspiration and parts of the code more than obviously come from us. 

Annoying as even the licence requires that we're mentioned and they can't just copy stuff and claim its theirs.

**Comment by rubengees** [comment]
Looks like it's based off of SuperNova-emoji which this library is also based on (isn't it?). I don't think that's too bad, maybe we can steal some ideas from them too :)

**Comment by mario** [comment]
Aaaah, had no idea about the history of this library. Thanks for letting me know.

**Comment by vanniktech** [comment]
> Looks like it's based off of SuperNova-emoji which this library is also based on (isn't it?). I don't think that's too bad, maybe we can steal some ideas from them too :)

Yup true
