### ISSUE TITLE
Update README with new release

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#407]
Tons of new changes. LayoutFactory, emoji only, inputfilter etc

**Comment by mario** [comment]
You should do this :P

**Comment by vanniktech** [comment]
Planning to merge #409 and cut a new releasee, any objections @mario @rubengees ?

**Comment by mario** [comment]
I want an updated readme (for this particular issue), https://github.com/vanniktech/Emoji/issues/430 fixed, and also fixing this https://github.com/vanniktech/Emoji/pull/410 (this I'll do in the coming week). Is that ok?

**Comment by vanniktech** [comment]
Yep sure. Let's do a release next week

**Comment by vanniktech** [comment]
README i'll update when I do the release

**Comment by vanniktech** [comment]
https://github.com/vanniktech/Emoji/releases/tag/0.7.0 is out of the door
