### ISSUE TITLE
ee9b8ebb broke EmojiPopup for custom views using it

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#408]
I'll create a repro / sample soon

**Comment by mario** [comment]
Where is the sample? :)

**Comment by vanniktech** [comment]
Been stomped with work but haven't forgotten about this

**Comment by vanniktech** [comment]
There you go @mario  https://github.com/vanniktech/Emoji/pull/409

**Comment by mario** [comment]
Fixed by the PR? :)

**Comment by vanniktech** [comment]
Haven't forgotten about this. Will be busy the next 1-2 weeks though
