### ISSUE TITLE
Allow adjustments to offset cost of 250ms delay

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#412]
Modify the keyboard height builder parameter to allow setting ONLY initial height thus offsetting 250ms delay in case you can get keyboard height earlier (which most apps do, say in their login screens).

**Comment by vanniktech** [comment]
Still relevant?

**Comment by mario** [comment]
With the existing PR, yes. But I'm still thinking about this.

**Comment by vanniktech** [comment]
What's the state here @mario ?

**Comment by vanniktech** [comment]
Let's make it configurable if anyone actually needs it.
