### ISSUE TITLE
Server gets [ "=\u0001" ] like Unicode strings for emoji while sent from client application.

### ISSUE THREAD

**Issue by Mr-Ramzan** [vanniktech/Emoji#418]
I am using [0.6.0 ] version ---- IOS type Emoji.

I am having an issue while sending emoji to the server as they get converted to some random Unicode strings. Encoding I am using for my send data is  UTF-8, and I am converting data before sending it to byteArray(Charsets.UTF-8).
![image](https://user-images.githubusercontent.com/36961360/69005195-4f3a5000-0940-11ea-9934-94f25bb41d20.png)
The above image shows how they get stored in DB.

**Comment by mario** [comment]
Issue with the way you send stuff/store it, not with the lib - sorry.
