### ISSUE TITLE
Emoji Replace - Some male Emoji replace to female

### ISSUE THREAD

**Issue by flexsingit** [vanniktech/Emoji#421]
Some male emoji replace to female emoji. I have tested on below mention devices.
1. Samsung Note 9
2. Samsung Note II

**- Library:**
implementation 'com.vanniktech:emoji-ios:0.6.0'
EmojiManager.install(new IosEmojiProvider());

Also try by replacing link with library module.
Please suggest how to resolve this issue.

![IMG-20191125-WA0000](https://user-images.githubusercontent.com/25687998/69604121-914f4a00-1042-11ea-97ed-59890290b52d.jpg)

**Comment by vanniktech** [comment]
I don't follow. As to my knowledge this works correctly.
