### ISSUE TITLE
emojiPopup and keyboard overlap

### ISSUE THREAD

**Issue by whysusu** [vanniktech/Emoji#424]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:0.5.1
- Affected devices: HUAWEI P30
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------_
![TIM图片20200113152421](https://user-images.githubusercontent.com/20158520/72238830-f6262a00-3619-11ea-9303-2be24c0d06a5.jpg)

**Comment by vanniktech** [comment]
Please try the latest snapshot.
