### ISSUE TITLE
Emojipopup.toggle working on API 27 and less but not working on API 28

### ISSUE THREAD

**Issue by nasirlordno1** [vanniktech/Emoji#427]
- Version of the library: tried both 0.6.0 and 0.7.0
- Affected versions: API 28

I am using this library for my project ,on button click its supposed to show emoji keyboard,its working correctly on All devices with API 27 or less but same code not working on API 28,i have tried 3 devices with API 28.

public void setUpEmojiPopup() {
        emojiPopup = EmojiPopup.Builder.fromRootView(rootView)
                .setOnEmojiBackspaceClickListener(ignore -> Log.d(TAG, "Clicked on Backspace"))
                .setOnEmojiClickListener((ignore, ignore2) -> {
                    final String text = editText.getText().toString().trim();
                    addTextSticker(text);
                    Log.d(TAG, "Clicked on emoji");
                })
                //.setOnEmojiPopupShownListener(() -> emojiButton.setImageResource(R.drawable.ic_keyboard))
                .setOnSoftKeyboardOpenListener(ignore -> Log.d(TAG, "Opened soft keyboard"))
                //.setOnEmojiPopupDismissListener(() -> emojiButton.setImageResource(R.drawable.emoji_ios_category_smileysandpeople))
                .setOnSoftKeyboardCloseListener(() -> Log.d(TAG, "Closed soft keyboard"))
                .setKeyboardAnimationStyle(R.style.emoji_fade_animation_style)
                .setPageTransformer(new PageTransformer_emoji())
                .build(editText);
    }

this is the code. Anyone knows whats the problem?

**Comment by vanniktech** [comment]
Can you check with master version?

**Comment by nasirlordno1** [comment]
It working on master version .

**Comment by vanniktech** [comment]
Then please use the snapshot version for now.
