### ISSUE TITLE
How to add custom button to categories tabs?

### ISSUE THREAD

**Issue by AlexMercier** [vanniktech/Emoji#428]
Does this library support method to add custom button to categories tabs?
I want to add "Show Keyboard" button as first item in tab
![2020-03-04_215501](https://user-images.githubusercontent.com/6580198/75913407-ebdb1c00-5e63-11ea-8b9f-467d70f99482.png)

**Comment by vanniktech** [comment]
Show keyboard isn't possible and we would not want that.

**Comment by AlexMercier** [comment]
> Show keyboard isn't possible and we would not want that.
Ok, but can I add custom button with custom action to categories tabs panel?

**Comment by vanniktech** [comment]
You can add just emojis yes.

https://github.com/vanniktech/Emoji/blob/master/emoji/src/main/java/com/vanniktech/emoji/emoji/EmojiCategory.java
