### ISSUE TITLE
load wrong emoji EmojiTextView android < 8.0

### ISSUE THREAD

**Issue by binhhoit** [vanniktech/Emoji#429]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.6.0
- Affected devices: HTC M9 and Sony XA plus
- Affected versions: android < 8.0 

Screenshot(s) showing the issue and reprodution steps are appreciated.
error android 7 HTC
![image](https://user-images.githubusercontent.com/29090540/77519378-f5c7cc00-6eb1-11ea-854c-a74dd1ecefc6.png)
and I using android > 8.0 
![Screen Shot 2020-03-25 at 4 03 10 PM](https://user-images.githubusercontent.com/29090540/77519476-260f6a80-6eb2-11ea-933c-5d0a99b11dd4.png)

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Please try out the sample and use the latest commit from master.

**Comment by binhhoit** [comment]
Hi @vanniktech,
I am using vs implementation 'com.vanniktech:emoji-ios:0.6.0' and error.
But Do you have new vs release?

**Comment by binhhoit** [comment]
I using emoji of iPhone comment and reading in android vs <9.0. I thing android can't load it, you try ex icon above image.
