### ISSUE TITLE
Update README with Facebook emojis & screenshots

### ISSUE THREAD

**Issue by mario** [vanniktech/Emoji#430]
Thanks :D

**Comment by mario** [comment]
@vanniktech I'll have time for my one remaining ticket tonight. Can you please prepare a README PR with this and the other things we added so I can look into it? :)

Thanks!

**Comment by vanniktech** [comment]
I'll do this once we've got everything otherwise some things are missing

**Comment by vanniktech** [comment]
Will do this with #407
