### ISSUE TITLE
Possible licensing issues for actual emoji glyphs

### ISSUE THREAD

**Issue by grizzlyuser** [vanniktech/Emoji#433]
- Version of the library: 0.7.0 (In development), master branch, commit d13e8fa273b20bd373f3479e4433f2961c978c30
- Affected devices: Possibly all
- Affected versions: Possibly all

It seems that some of the actual emoji glyphs available in this repository are proprietary and not compatible with the license of the current project (Apache 2.0).

For example, for [Apple emoji set](https://github.com/vanniktech/Emoji/tree/master/emoji-ios/src/main/res/drawable-nodpi) please take a look at the following:
https://blog.emojipedia.org/apples-emoji-crackdown/
https://stackoverflow.com/questions/22337295/license-of-apple-color-emoji-ttf/22949517#22949517

So it may turn out that you may not be legally allowed to use and/or distribute them.

I didn't check the licensing of other emoji sets available. This issue is just a warning that this repo may (or may not) face something like DMCA takedown in future.

**Comment by vanniktech** [comment]
I'm wondering how come we can download them from our source then. @rubengees do you know anything?

Worst case we'll ditch iOS emojis. I haven't used them in months. Switched to Google's Emojis.

**Comment by rubengees** [comment]
Obligatory IANAL.

Our source simply extracts them from the fonts on macOS. It's not like they are from an official source. There seems to be no license for apple emojis so I'm not sure if it's fine to use them without getting an agreement. But I also never heard of Apple to complain about inappropriate usage und if it's fine to distribute the images in a library in the middle like we do or not.

**Comment by grizzlyuser** [comment]
AFAIK, if there's no license, then it's proprietary by default. Please see https://www.gnu.org/licenses/license-list.html#NoLicense

Examples of Apple enforcement are available in the issue description. If the project is going to keep these emoji, it won't hurt to ask Apple for permission. But for a true FLOSS project, I think it's better to just stay away from all non-free stuff.

**Comment by vanniktech** [comment]
For now let's sit this out. If our source get's rid of ios emojis, we'll do the same. Thanks for raising this poiint @grizzlyuser
