### ISSUE TITLE
Android not supporting Factory Worker emoji

### ISSUE THREAD

**Issue by nAkhmedov** [vanniktech/Emoji#438]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.6.0
- Affected devices: Nexus 5
- Affected versions: 6.0.1

https://emojipedia.org/factory-worker/

🧑‍🏭

If i receive this emoji from iOS, it is appearing person + factory emoji

![image](https://user-images.githubusercontent.com/8067423/81162959-7268c280-8fa7-11ea-9e80-8e6d37e3e9a3.png)

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
There's something wrong with your string handling, this works in many apps that I'm working on
