### ISSUE TITLE
Emoji popup coming above the keyboard

### ISSUE THREAD

**Issue by jeeke** [vanniktech/Emoji#439]
- Version of the library: 0.6.0
- Affected devices: Pixel 3a XL Emulator

![Screenshot_1588788391](https://user-images.githubusercontent.com/58397433/81213022-6571c080-8ff3-11ea-82c4-1fbe6b31cc06.png)

**Comment by mario** [comment]
Use master

**Comment by jeeke** [comment]
Already on master

![Screenshot_1588790335](https://user-images.githubusercontent.com/58397433/81215736-64db2900-8ff7-11ea-9e7a-f2424662db7b.png)

**Comment by vanniktech** [comment]
@mario what could be the reason for this?

**Comment by mario** [comment]
Not instantiating early enough?  Unless there's a minimal sample I can use to reproduce...

**Comment by vanniktech** [comment]
It's the sample app he's using.

**Comment by vanniktech** [comment]
Thanks for fixing it in #452
