### ISSUE TITLE
Memory leak EmojiPopup #369 not solved?

### ISSUE THREAD

**Issue by themadmrj** [vanniktech/Emoji#441]
Using the last available version (0.7.0-SNAPSHOT) which includes the `OnAttachStateChangeListener`, I still have a memory leak, both on android 7 (physical device) and emulator (android 9 or 10). 
I used 0.7.0-SNAPSHOT instead of master exactly because, but in the end, instead of leaking the `OnGlobalLayoutListener`, `EmojiPopup.java` leaks `onAttachStateChangeListener` in my case.
CanaryLeaks gives the following output:
![Screenshot_20200511-223317](https://user-images.githubusercontent.com/11475495/81609667-93cb1380-93d8-11ea-8e22-1499ac1227ba.png)
![Screenshot_20200511-223324](https://user-images.githubusercontent.com/11475495/81609669-94fc4080-93d8-11ea-9e96-63bb50f50725.png)
![Screenshot_20200511-223332](https://user-images.githubusercontent.com/11475495/81609671-9594d700-93d8-11ea-8336-d122c3c4cc1c.png)

**Comment by themadmrj** [comment]
Ok, so I integrated your library in my project to be able to edit the code and after a few tests, I noticed `onViewDetachedFromWindow` is never called when switching to another `Fragment`. That's the problem, since as detailed here [https://stackoverflow.com/questions/29021316/when-are-views-attached-and-detached](url), there is no garantee that the `View` is detached. Therefore relying on `onViewDetachedFromWindow` to clean up is a mistake.
Sadly, there is no method like `Fragment.onDestroyView()` for a `View`. Therefore the simplest solution I found at the moment is not integrating the cleanup in `EmojiPopup`, but making `EmojiPopup.stop()` public and calling it inside the`Fragment`  from `Fragment.onDestroyView()`.

**Comment by vanniktech** [comment]
@mario your thoughts?

**Comment by vanniktech** [comment]
Huh. In my code I'm settting `emojiPopup` to null which should do the job.

**Comment by themadmrj** [comment]
> Huh. In my code I'm settting `emojiPopup` to null which should do the job.

That does not work for me

**Comment by vanniktech** [comment]
Why? Make it nullable and clear it in your appropriate Fragment lifecycle method
