### ISSUE TITLE
MainDialog ORIENTATION_LANDSCAPE ,emojiPopup and keyboard overlap

### ISSUE THREAD

**Issue by LuoYang2412** [vanniktech/Emoji#444]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: master branch
- Affected devices: OnePlus A5000
- Affected versions: Android 9

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------
Layout Inspector ok
![IMG_20200531_124014](https://user-images.githubusercontent.com/15208837/83344984-7ab2e400-a340-11ea-90be-59435ca0c2e2.jpg)

devices error
![Screenshot_20200531-123945](https://user-images.githubusercontent.com/15208837/83345013-ccf40500-a340-11ea-9ce6-8ad10027c0cf.jpg)

**Comment by vanniktech** [comment]
Interesting. Being honest, I'm not using landspace. Mind trying to submit a PR that fixes this?

**Comment by mario** [comment]
Is this in the sample app?

**Comment by vanniktech** [comment]
Yeah.

**Comment by vanniktech** [comment]
Can you please try with the changes from #452?
