### ISSUE TITLE
EmojiUtils.isOnlyEmojis("⭐️") returns false

### ISSUE THREAD

**Issue by chinnychin19** [vanniktech/Emoji#449]
- Version of the library: `com.vanniktech:emoji-google:0.6.0`
- Affected devices: *
- Affected versions: *

Repro:

```java
String s = "⭐️⭐️⭐️";
boolean isOnlyEmojis = EmojiUtils.isOnlyEmojis(s); // returns false! this should be true
int emojisCount = EmojiUtils.emojisCount(s); // returns 3, which is correct
List<EmojiRange> emojis = EmojiUtils.emojis(s); // returns 3 ranges of [0,1), [2,3), and [4,5); note the gaps at 1, 3, and 5
```

**Comment by chinnychin19** [comment]
update: I think this is because sometimes stars include a [`\u65039`](https://www.fileformat.info/info/unicode/char/fe0f/index.htm) after them. It is called a `VARIATION SELECTOR-16` and I think it's incorrectly not being included as part of the emoji.

**Comment by vanniktech** [comment]
There exists a mechanism to detect duplicate emojis. Emoji takes a `isDuplicate` boolean and only the generator would need to be changed.

https://github.com/vanniktech/Emoji/blob/master/generator/index.js#L52

**Comment by vanniktech** [comment]
@chinnychin19 do you want to contribute the change?

**Comment by vanniktech** [comment]
Never mind. I've got it.
