### ISSUE TITLE
EmojiKeyboard wrong initial height in fragment

### ISSUE THREAD

**Issue by SourceEngine** [vanniktech/Emoji#451]
- Version of the library: 0.6.0
- Affected devices: Tested on Samsung S8 - S10, Huawei, Xiaomi, Motorola (presumably more devices affected)
- Affected versions: Android 7.1 - 9

**Image showing the error is attatched bellow**

Currently iam implementing the `EmojiKeyboard` in a `BottomSheetDialog`.
I have tried building the `EmojiPopup` as followed:

```
@Override
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup c, @Nullable Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.layout, c, false);
        return view;
    }
```

```
    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        emojiPopup = EmojiPopup.Builder.fromRootView(this.view).build(this.view.findViewById(R.id.etxt_emoji));
    }
```

When pressing the `EditText` i open the `EmojiKeyboard`:
```
etxt_emoji.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                if (!emojiPopup.isShowing()) {
                    emojiPopup.toggle();
                }
                etxt_emoji.requestFocus();
                return false;
            }
        });
```

Now the `EmojiKeyboard` opens as the image below shows. 
After closing the keyboard and tapping the `Edittext` again the EmojiKeyboard opens normally.

Could you please have a look at this? Maybe iam doing something wrong?

Thanks in advance!

![emoji_error](https://user-images.githubusercontent.com/62891392/85124913-fa8aea80-b22a-11ea-82c7-ad1bafc6edae.png)

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Yeah. Can you try with https://github.com/vanniktech/Emoji/pull/448 ?

**Comment by SourceEngine** [comment]
I have tried it as #448 describes:
```
if (builder.keyboardAnimationStyle != 0) {
      popupWindow.setAnimationStyle(builder.keyboardAnimationStyle);
    }

    // Root view might already be laid out in which case we need to manually call start()
    if (rootView.getParent() != null) {
      start();
    }

    rootView.addOnAttachStateChangeListener(onAttachStateChangeListener);
```

Sadly still the same result

**Comment by vanniktech** [comment]
The view should have a parent though, should not it?

**Comment by vanniktech** [comment]
Also, please test out the latest master, there were some bug fixes.
