### ISSUE TITLE
Classes are public but constructors are not!

### ISSUE THREAD

**Issue by sha256** [vanniktech/Emoji#464]
Hi, Thanks for the awesome library!

I think this library could offer a great deal of customization. The only problem is, using package private constructors instead of public constructor. For example:

classes are declared like this:
`public final class EmojiPagerAdapter`

but constructors are: 
`EmojiPagerAdapter(final OnEmojiClickListener listener,
                    final OnEmojiLongClickListener longListener,
                    final RecentEmoji recentEmoji, final VariantEmoji variantManager) `

There are few cases like this. If you're open to update it, I can submit a pull request.

**Comment by vanniktech** [comment]
Probably a mistake. I don't want people to reuse the internals.
