### ISSUE TITLE
toggle() not showing emoji keyboard

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#468]
library 'com.vanniktech:emoji-ios:0.7.0'
i tested it on android 9 and 10 
samsung A30 s

the error is very similar to this problem https://github.com/vanniktech/Emoji/issues/450

but when i use toggle() never shows the emoji keyboard just open the normal keyboard
but if i use show() the second time i use show() the emoji keyboard is showed but it takes the whole screen

i use emoji keyboard in two actvities
chat activity = there works well toggle() no problems
profile activity = there fails toggle() i dont know maybe it is because i have other editTexts on that activity but the others 
editTexts are normal editTexts no emoji editTexts

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Try reproing somehow in the demo app - otherwise feel free to take a stab at a PR.

**Comment by hvar90** [comment]
i just could discover 2 things 
using com.vanniktech:emoji-ios:0.6.0 works well
and when i do not call 
emojiPopup.dismiss(); 
on the SoftKeyboardCloseListener
the behaviour change a little 
this happens : if the toggle() method is called twice the  the emoji keyboard is showed but it takes the whole screen
but if i call emojiPopup.dismiss(); on the SoftKeyboardCloseListener
calling   toggle() 1 or many times never show anything

i think maybe the emojiPopup is called too fast and later the keyboard closes the emojipopup and it is showed

so i dont know more info about the problem
is there a easy option to debug the library step by step ? 


is there a option to debug the library ?

**Comment by vanniktech** [comment]
> is there a easy option to debug the library step by step ?

Yeah take the first step and wind down. Other than that, no.

**Comment by hvar90** [comment]
how can use the library as a module ?
i downloaded the library but when i try to use it
i get messages like "Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist"
what is the correct configuration to use the library as a local module 

i want to test and chage locally the code of the library to identify and resolve the problem

**Comment by vanniktech** [comment]
Clone this repository and use the sample app

**Comment by hvar90** [comment]
i tried to reproing my problem with the sample app but there everthing works well
only in my code works bad and i do not know where is coming the problem

**Comment by vanniktech** [comment]
Then the problem is on your side. If you can repro in the sample, feel free to write here again.

**Comment by hvar90** [comment]
i could not find the problem but i could find the solution 
```
<activity
android:name=".myActivity"
android:label="@string/myLabel"
android:windowSoftInputMode="stateVisible|adjustResize" />
```

i think on some situations the popup has a weird behaviour and writing on manifest 
this android:windowSoftInputMode="stateVisible|adjustResize"
the problem is fixed
