### ISSUE TITLE
Getting a major error after importing the class

### ISSUE THREAD

**Issue by steveo199** [vanniktech/Emoji#47]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.4
- Affected devices:
- Affected versions:

problem is I am getting this, I imported the jar and the aar file.
Could not initialize class com.vanniktech.emoji.EmojiHandler
Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
EmojiHandler is a package protected final class which means you can't instantiate it

**Comment by steveo199** [comment]
thanks  it was my mistake.

**Comment by vanniktech** [comment]
Alright will close then.
