### ISSUE TITLE
EmojiPopup.Builder.fromRootView() reads from the disk on the main thread

### ISSUE THREAD

**Issue by lukesleeman** [vanniktech/Emoji#476]
`EmojiPopup.Builder.fromRootView()` performs a read from the disk on the main thread.   This is caused by the builder constructing a `RecentEmojiManager` in its constructor:

https://github.com/vanniktech/Emoji/blob/6d33b3a68ed9b3102c8d574a7669d44d7da1a57b/emoji/src/main/java/com/vanniktech/emoji/EmojiPopup.java#L373

The `RecentEmojiManager` then creates a shared preferences instance, which then causes the main thread disk read.  In our case this causes problems as we are running with strict mode enabled, and we are building our own `RecentEmoji` instance, so we don't even use the one that gets made in the constructor.

There are a few ways we can address this issue.   I think the most straightforward approach would be to modify the `EmojiPopup.Builder` so that the `recentEmoji` field is `@Nullable` then construct a `RecentEmojiManager` inside the `build` method if `recentEmoji` is still null.  That way people can set their own emoji managers and manage the threading of any disk reads in whatever way suits them.

All up it seems like a pretty minor change.  @vanniktech would you be happy to accept a PR along these lines?  I could submit something.

**Comment by vanniktech** [comment]
Yes sure, PR sounds good.

**Comment by lukesleeman** [comment]
I've submitted a small PR which fixes the issue https://github.com/vanniktech/Emoji/pull/478
