### ISSUE TITLE
Disable RecentEmoji

### ISSUE THREAD

**Issue by keyvanNorouzi** [vanniktech/Emoji#477]
Is there any way to disable the RecentEmoji tab? (version 0.7.0)
I want to dismiss the Recent Emojis

**Comment by lukesleeman** [comment]
We have a similar need, and I would be happy to submit a PR.

Digging through the code the recent emoji come from the `EmojiPopup.Builder`, get passed into the `EmojiPopup`, and from there into the `EmojiView` where a `EmojiPagerAdapter` is build with the recent emoji as its first page.

I can think of two approaches to to represent the "No recent emoji please" case:

**Option 1 - Represent it as `null` `recentEmoji` field in the builder and pass the null along to emoji view, etc**
This is easy enough to do - unfortunately it introduces a null into the codebase, and we will need a whole bunch of null checks in various places.  Its possible somebody will miss a null check at some stage and the library will crash.  This also has the disadvantage of representing a "Business state" of "I don't want recent emoji" by an instance variable being `null` which could be a bit obscure.

**Option 2 - Create some sort of marker implementation of `RecentEmoji` - perhaps an `NoRecentEmoji` **
We could create a singleton object `RecentEmoji` which implements the `RecentEmoji` interface with empty operations.  Inside the `EmojiView` and `EmojiPagerAdapter` we can check to see if the `recentEmoji` field is `NoRecentEmoji` and remove that page from the adapter.

@vanniktech which approach do you think would be best for this codebase?  If it was kotlin I would probably go with option 2, but this is old school java, so perhaps some more nulls aren't that bad 🙂

**Comment by vanniktech** [comment]
Option 2 sounds good.

**Comment by vanniktech** [comment]
PR welcome.
