### ISSUE TITLE
Not Able to compile project in Android Studio 4.1.1

### ISSUE THREAD

**Issue by trueman1** [vanniktech/Emoji#479]
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform emoji-twitter-0.7.0.aar (com.vanniktech:emoji-twitter:0.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /home/oru/.gradle/caches/transforms-2/files-2.1/1437f4b79a5aee850ea960e1c4aa63d2/jetified-emoji-twitter-0.7.0.
         > AAPT2 aapt2-4.1.1-6503028-linux Daemon #0: Unexpected error during compile '/home/oru/.gradle/caches/transforms-2/files-2.1/1437f4b79a5aee850ea960e1c4aa63d2/jetified-emoji-twitter-0.7.0/res/drawable-nodpi-v4/emoji_twitter_sheet_20.png', attempting to stop daemon.
           This should not happen under normal circumstances, please file an issue if it does.

The build.gradle looks like this - 
`plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId "com.example.test41"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation('com.vanniktech:emoji-twitter:0.7.0')
 
}`

**Comment by vanniktech** [comment]
You need AndroidX.
