### ISSUE TITLE
Keyboard flash and new interface

### ISSUE THREAD

**Issue by Meglali20** [vanniktech/Emoji#483]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.7.0
- Affected devices: Emulator API 29 and physical device API 26
- Affected versions: Twitter

Screenshot(s) showing the issue and reproduction steps are appreciated.

----------------------------------------------------------------------

When I show emojiPopup it flashes the keyboard and after it shows the EmojiPopup, how to show EmojiPopup instantly? 
There is OnEmojiClickListener, how about implementing a long click listener for emojis?
Thank you.

**Comment by 207ashu** [comment]
i found the similar issue on my device, I have set the keyboard theme to green knowingly.

https://user-images.githubusercontent.com/23443023/102961938-ac251400-450b-11eb-91e5-fd0024e45e6a.mp4

**Comment by 207ashu** [comment]
can it be that we first launch the emoticon panel and not the ime behind it ?

**Comment by Meglali20** [comment]
@207ashu What do you mean?

**Comment by 207ashu** [comment]
I mean just like whatsapp has its own inbuilt emoji section wherein the keyboard shows on top of the emoji panel, but with the use of library emoji popup appears on top of the keyboard section

**Comment by Meglali20** [comment]
@207ashu yes, I didn't take a look at the library code but I think it shows the keyboard before to get the height and use it for the emoji popup, needs a confirmation.
I think this repo isn't supported anymore,  I get issues like the one I mentioned, sometimes the emoji popup shows above the keyboard and sometimes it takes the full height and you can't dismiss it...

**Comment by Meglali20** [comment]
#213 One more issue.

**Comment by vanniktech** [comment]
I don't see anything wrong here.
