### ISSUE TITLE
Incorrect heart emoji detection in EmojiUtils

### ISSUE THREAD

**Issue by vellrya** [vanniktech/Emoji#484]
- Version of the library: 0.7.0
- Affected devices: OnePlus 3
- Affected versions: Android 8.0

----------------------------------------------------------------------

Hello, some strange behaviour:
EmojiUtils.emojisCount("❤") return 0. 
Heart symbol is also ignored in method EmojiUtils.emojis (empty list returned).

Thats all, thank you for time spend on maintaing library :)

**Comment by vanniktech** [comment]
Dupe of #485
