### ISSUE TITLE
A space appears at the bottom of the keyboard

### ISSUE THREAD

**Issue by Mr-Saidov** [vanniktech/Emoji#489]
A space appears at the bottom of the keyboard

- Version of the library: 0.7.0
- Affected devices: Xiaomi Note 6 Pro, Redmi 7A
- Affected versions:

Screenshot(s) showing the issue and reprodutio
![Screenshot_2021-02-27-00-12-29-585_com vanniktech emoji sample](https://user-images.githubusercontent.com/45036079/109344755-ff5f6e00-7890-11eb-9838-05a61c64cbc4.jpg)
n steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Dupe of #467
