### ISSUE TITLE
EmojiEditText cursor height is too small by wirting emojis followed by text

### ISSUE THREAD

**Issue by denjoo** [vanniktech/Emoji#492]
If you write an emoji followed by a text. The height of the emoji cursor is too small and the textfield height reduce. If you write text the textfield increase. Because the line height is bigger. Solution: It should be the same line height. 

- Version of the library: 0.7.0
- Affected devices: all
- Affected versions: 0.7.0

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Open PR (from you): https://github.com/vanniktech/Emoji/pull/493
