### ISSUE TITLE
Failed to resolve: com.vanniktech:emoji:0.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by andansky** [vanniktech/Emoji#53]
Hi,Thanks for sharing.
Failed to resolve: com.vanniktech:emoji:0.4.0-SNAPSHOT

This proplem how do solved?

**Comment by vanniktech** [comment]
@andansky Did you add

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by andansky** [comment]
oh,thanks。I can use now。But I think you should write this in readme。

**Comment by vanniktech** [comment]
I'll. I thought this is common knowledge but I got this question already a couple of times.

**Comment by vanniktech** [comment]
#54
