### ISSUE TITLE
Emojis fill the entire screen when using hardware keyboard.

### ISSUE THREAD

**Issue by Janneman84** [vanniktech/Emoji#535]
- Version of the library:
0.7.0 (latest at time of writing)
- Affected devices:
All devices with hardware keyboard connected
- Steps to reproduce:
Use a Chromebook or connect a Bluetooth/USB keyboard to phone, then run the sample project on it and press the smiley.

Same symptom as here:
https://github.com/vanniktech/Emoji/issues/474

Entire screen gets filled with the emoji view, getting you stuck. This happens on my Chromebook because it has a hardware keyboard. I also connected a Bluetooth keyboard to my phone and the same issue appears here too. I used the demo project to test.

The main reason for wanting to use this package is because you can't type emojis with a hardware keyboard at all, while with most soft keyboards you can.

**Comment by vanniktech** [comment]
@Janneman84 can you debug this and provide a workaround? I don't have a Chromebook / physical keyboard.

**Comment by vanniktech** [comment]
Closing in favor of #474
