### ISSUE TITLE
Wrong borders at the bottom

### ISSUE THREAD

**Issue by kojid0** [vanniktech/Emoji#538]
Element Messenger included the Emoji library.
[I encountered a bug](https://github.com/vector-im/element-android/issues/2647) where the emoji picker has a wrong border at the bottom. 

![image](https://user-images.githubusercontent.com/24477557/104090245-d00b8800-5275-11eb-9ab4-803f33732238.png)

Using a Google Pixel 5 with [FlorisBoard Keyboard](https://github.com/florisboard/florisboard).

**Comment by vanniktech** [comment]
@kojid0 that thing is coming from the keyboard itself and it seems like our `PopupWindow` is added on the z axis after the keyboard input (letters etc) but before their navigation elements.

Do you have an idea how we can tell Android to place our PopupWindow at the very top?

**Comment by vanniktech** [comment]
Another related case: 

![Another related case](https://user-images.githubusercontent.com/20623299/239519969-9493a467-e947-4dee-9415-53f2225020a2.jpg)

**Comment by vanniktech** [comment]
Same as https://github.com/vanniktech/Emoji/issues/758
