### ISSUE TITLE
Library is Not Compaitable with latest version of Android SDK

### ISSUE THREAD

**Issue by surajsahani** [vanniktech/Emoji#543]
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.vanniktech:emoji-material:0.8.0] /home/martial/.gradle/caches/transforms-2/files-2.1/4cd6eb85323998764738450e4d2a16a4/jetified-emoji-material-0.8.0/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.vanniktech.emoji.material" to force usage (may lead to runtime failures)

----------------------------------------------------------------------

**Comment by Zhuinden** [comment]
it says the library requires minSdk 21, and your project has minSdk 16

**Comment by vanniktech** [comment]
That's true
