### ISSUE TITLE
Opening emoticons, and change the keybord

### ISSUE THREAD

**Issue by Andrzej1991** [vanniktech/Emoji#57]
Whenever i open the emoticons with button and change to keybord and hide it (call method dismiss();) i lost focus to rootView so then i can open emoticonsSelect but i no have a the rootView
This open:

private void showEmoticon() {
        imageEmoticonButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                    emojiPopup.toggle();
            }
        });
    }

i setup on OnCreateView  (fragment)

 private void setUpEmojiPopup() {
        emojiPopup = EmojiPopup.Builder.fromRootView(sendPanel).setOnEmojiBackspaceClickListener(new OnEmojiBackspaceClickListener() {
            @Override
            public void onEmojiBackspaceClicked(final View v) {
            }
        }).setOnEmojiClickedListener(new OnEmojiClickedListener() {
            @Override
            public void onEmojiClicked(final Emoji emoji) {
            }
        }).setOnEmojiPopupShownListener(new OnEmojiPopupShownListener() {
            @Override
            public void onEmojiPopupShown() {
                //      imageEmoticonButton.setEnabled(false);
            }
        }).setOnSoftKeyboardOpenListener(new OnSoftKeyboardOpenListener() {
            @Override
            public void onKeyboardOpen(final int keyBoardHeight) {
//                emojiPopup.dismiss();
            }
        }).setOnEmojiPopupDismissListener(new OnEmojiPopupDismissListener() {
            @Override
            public void onEmojiPopupDismiss() {
            }
        }).setOnSoftKeyboardCloseListener(new OnSoftKeyboardCloseListener() {
            @Override
            public void onKeyboardClose() {
                emojiPopup.dismiss();
            }
        }).build(messageBox);
    }

**Comment by Andrzej1991** [comment]
I see other issue like this on closed issues. I try to help you resolve it. also pls look on Dismiss method. this method remove global root.

**Comment by vanniktech** [comment]
Does the sample work for you?

**Comment by Andrzej1991** [comment]
nope. I use now version 2.0 and its work 3.0 doesnt work

**Comment by vanniktech** [comment]
Alright that's good to know does 0.2.0 work for you on all devices?

**Comment by Andrzej1991** [comment]
Yea, i try on Huawei P9, Samsung Galaxy S5, S4, and on Sony xperia Z1, also on nexus emulator

**Comment by vanniktech** [comment]
Alright I'll try to see what changed between the versions in the next few days if I find some time for it.

**Comment by vanniktech** [comment]
I'll close this as this should be fixed with `0.4.0-SNAPSHOT`. If it isn't please create / reopen the issue. I'll cut a release soon.
