### ISSUE TITLE
Emoji not working with DialogFragment

### ISSUE THREAD

**Issue by rinlv** [vanniktech/Emoji#61]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:
- Version of the library: 0.3.0
- Affected devices: Nexus 6
- Affected versions: API 23

Screenshot(s) showing the issue and reprodution steps are appreciated.

---

I was using emoji for edittext in DialogFragment. But when i toggle, keyboard still display. Please check this issue. Thanks.

**Comment by vanniktech** [comment]
Is this the same issue as #26

**Comment by vanniktech** [comment]
I'll close this as this should be fixed with `0.4.0-SNAPSHOT`. If it isn't please create / reopen the issue.
