### ISSUE TITLE
Require Data Binding support.

### ISSUE THREAD

**Issue by naushad-madakiya** [vanniktech/Emoji#74]
Need Data Binding support for `EmojiTextView.Java`. In my Chat application, I am using Data Binding and EmojiTextView need to be bindable for Chat Messages.

Will need to enable data binding in `build.gradle` . I can make PR if you guys are ok with binding support.

**Comment by vanniktech** [comment]
I'm not a fan of data binding. And why does the library need to enable it? I don't quite get it.

**Comment by naushad-madakiya** [comment]
The project which will be using Data Binding and also using this library so the project can directly bind data to `EmojiTextView`. `EmojiTextView` is inside the library so if the library will enable data binding from gradle then the only project will be able to bind `EmojiTextView`.

The same issue I had with my project. What I did is added lib as a module and added `dataBinding.enabled = true` in gradle of lib.

**Comment by vanniktech** [comment]
How does this flag affect non data binding users?

**Comment by naushad-madakiya** [comment]
It won't affect or make any changes in existing implementation for non data binding users but as an addon, if user want to use data binding and use `EmojiTextView` in `RecyclerView`.

**Comment by vanniktech** [comment]
Can't you add data binding support for this library on your side (consumer)? I'm absolutely against Data binding and don't want this library to support it.
