### ISSUE TITLE
Proposal: Switch to EmojiOne

### ISSUE THREAD

**Issue by rubengees** [vanniktech/Emoji#75]
This is a proposal for a large change in the library.

I think about switching to the emoji of [EmojiOne](http://emojione.com/). It is regularly updated, contains all of the latest emoji, has a friendly licence (creative commons) and provides mapping files for somewhat easy generation of mapping classes. 

### Benefits
- All of the missing emoji would be added #10, #11, #12.
- Integration of skin tones #34 (Not as a popup menu, but still better than not having them altogether).
- Looks also good on large displays 
- Nearly automatic updates possible, see down below.

### Caveats
- The library might grow in size, I'm not far enough to say that certainly.

### How I would approach this
- Write a small script for cloning the EmojiOne repo -> Copying the relevant resources -> Generate `.java` files which map to correct values. This has the advantage that we could just rerun the script when files of EmojiOne have changed and simply copy the changes to the library.
- Rewrite/Simplify the library to be compatible with the changes.

### Preview (Work in progress)
![device-2017-01-06-181100](https://cloud.githubusercontent.com/assets/8021265/21726470/1ce400b4-d43d-11e6-8819-4131f516a669.png)

What do you think about this? I would happily submit a PR for that (in fact I'm already working on it, the script is nearly ready).

**Comment by vanniktech** [comment]
What do you think of providing support for both (maybe as a separate artifact)?

**Comment by rubengees** [comment]
Hmm, I don't know if that would be (easily) possible as the current approach and the new one would be somewhat different and hard to to abstract into one solution. But I will look into it.

**Comment by rubengees** [comment]
On second thought: Why would you like to keep the old ones? For backward support? As I noticed nobody is using the old iOS ones anymore (WhatsApp, Telegram, ...).

**Comment by vanniktech** [comment]
If so they'd need to be different artifacts hence also different library modules. 

WhatsApp is now on Android using the newer iOS emojis which are also the ones this library should provide.

**Comment by rubengees** [comment]
I thought about something like a commons module with contains all the ui and managing part. Then there would be different modules, which the user could choose from, e.g. old-ios, emojione, android, whatever. But as I said I think that might be quite hard to get that working. Especially since the current emojis are mapped by hand. 

Ah, those are new iOS ones? Haven't used iOS for ages...
I looked for them, but couldn't find a repo or something parsable containing them.

**Comment by vanniktech** [comment]
Yeah I also didn't find them. Although I didn't look for them either. Common module might make sense although there's not that much common code.

**Comment by dotocan** [comment]
It would be great to switch to EmojiOne, i highly support this :)

**Comment by vanniktech** [comment]
I'll review @rubengees PR this week and want to get this going out too

**Comment by vanniktech** [comment]
Thanks once again for your amazing PR @rubengees
