### ISSUE TITLE
Things to do before merging #77

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/Emoji#78]
First of all thank you very much for your work @rubengees in #77.

There are a few things that I still want to talk about and hence a new issue since that PR is already way too long to get an overview about things.

- [X] Is this one needed - EmojiManager.getCategories() ?
- [X] ~When should the `destroy` method be called of the EmojiManager?~
- [X] ~Should we define an enum for categories? (To have type safety)~
- [X] Example Emoji One
- [X] Have emojis somewhat ordered logically so that they keep their order across new imports
- [X] Compression of images
- [X] restore old ios category order (it's different now)
- [X] Usage readme on how to update emojis
- [X] Exclude skin emojis in keyboard for now but display them in TextView
- [X] Old category icons for ios and the good looking ones for the new emoji one

Some more stuff might get added to the list as we tackle it down.

**Comment by rubengees** [comment]
> Is this one needed - EmojiManager.getCategories() ?

Yes, for the `EmojiView` for building it's tabs.

> When should the destroy method be called of the EmojiManager?

I added it mainly for tests, a User could call it when he is sure the `EmojiManager` is not needed any more and then release the memory of it (For example if there is a class `EmojiActivity` it calls `EmojiManager.install` in `onCreate` and `EmojiManager.destroy` in `onDestroy`). The recommended usage is in an `Application` subclass though.

> Should we define an enum for categories? (To have type safety)

Categories now do not have a name. Just an icon and the Emojis.

> old category icons for ios and the good looking ones for the emoji one

I'm still for dropping them or finding some with better resolution. What is the reason for including them?

> update sample to include emoji one somehow too (maybe in the toolbar as you suggested)

I will work on it now~

> compression of images

I have tried that, the benefit is minimal (just some KB with a serious amount of calculating time).

**Comment by vanniktech** [comment]
> The recommended usage is in an Application subclass though.

yeah but unfortunately you don't have an onDestroy mechanism there :/

> Categories now do not have a name. Just an icon and the Emojis. 

Nice I saw it.

> I'm still for dropping them or finding some with better resolution. What is the reason for including them?

I want the style not to change within the new version. You can just use the old ones.

> I have tried that, the benefit is minimal (just some KB with a serious amount of calculating time).

I'll try to figure out a way to compromise them to squeeze out a bit

**Comment by rubengees** [comment]
> yeah but unfortunately you don't have an onDestroy mechanism there :/

True, but if the user kills the App, the memory is reclaimed (Because the Application itself is destroyed), otherwise Android will kill the App, if memory is needed so nothing to worry about here, as this is the "Android way" - Retain things in memory until the system really needs it.

> I want the style not to change within the new version. You can just use the old ones.

Well then, I'll add them back in. After this PR is merged I'll look for some with better resolution.

> Compressing

I can add the step back into the script if you want, no need to do that manually.

**Comment by vanniktech** [comment]
How about removing the onDestroy method then?

Also `getInstance()`, `getCategories()` and `findEmoji()` can all be package private. (We want to only expose the methods the consumer really needs)

**Comment by rubengees** [comment]
I need that method in one of the tests. Maybe keep it public and annotate with `@VisibleForTesting`? (https://developer.android.com/reference/android/support/annotation/VisibleForTesting.html)

Hmm, I thought those methods might be usefull if the user wants do something apart from showing the keyboard. I even thought about adding some more utility methods so this lib would be an all-in-one solution for doing things with emojis, what do you think?

**Comment by vanniktech** [comment]
If you need it in the test and it's in the same package just remove the `public` modifier and you're good.

For now I would not open it up. Once we know what we really want we can.

**Comment by vanniktech** [comment]
Who's defining the order of the emojis in a category? They somehow seem to be mixed up.

Also all of the different skin emojis are listed after each other, if we don't have that long pressing mechanism we might want to show only one color in the 'emoji' keyboard. However in TextView we could support all of them.

**Comment by rubengees** [comment]
> Making non-public API package-protected for the `EmojiManager`

Done.

> Who's defining the order of the emojis in a category?

They are used in the order they are on the website I linked somewhere. I have not found anything parsable to order them properly. I'll have a look again...

> Skin emojis

I agree. I'll think of a way of excluding them for now.

> Sample

Having it in the same sample is not possible, as the drawable files have the same names. I'll make a copy for EmojiOne then.

**Comment by vanniktech** [comment]
@rubengees updated the issue again. So cool that you figured out the "right" ordering, how did you do that? Is it the change in `generator/index.js` ? 

Maybe it would also be cool to add a readme `UPDATING` that contains a simple step by step list what to do in order to regenerate all of the emojis for `ios` and `one`.

**Comment by rubengees** [comment]
Yup. I realized that the emoji.json I use (form gemoji), actually was in the right order. I just had to look up the index of each emoji then.
I've also tried to compress the images and rewrote the script a bit. 

> Maybe it would also be cool to add a readme UPDATING

Yes, I also thought about that. Will now write one.
After that I will work on excluding the skin toned ones from the keyboard.

**Comment by vanniktech** [comment]
All done
