### ISSUE TITLE
cannot find symbol class EmojiImageView emoji-ios:0.11.0

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#784]
i got a error with the new library
- Version of the library:
 emoji-ios:0.11.0
- Affected devices:
 samsung
- Affected versions:
 android 11

cannot find symbol class EmojiImageView
package com.vanniktech.emoji.emoji does not exist

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
The class is internal now: https://github.com/vanniktech/Emoji/blob/master/emoji/src/main/kotlin/com/vanniktech/emoji/internal/EmojiImageView.kt

Why do you need to use that class?

**Comment by hvar90** [comment]
for OnEmojiClickListener
also Cannot resolve symbol 'Builder'

EmojiPopup.Builder
```
private void setUpEmojiPopup() {
        emojiPopup = EmojiPopup.Builder.fromRootView(ns)              
                .setPageTransformer(new PageTransformer())
                .setOnEmojiBackspaceClickListener(new OnEmojiBackspaceClickListener() {
                    @Override
                    public void onEmojiBackspaceClick(final View v) {
                    }
                }).setOnEmojiClickListener(new OnEmojiClickListener() {
                    @Override
                    public void onEmojiClick(@NonNull final EmojiImageView imageView, @NonNull final Emoji emoji) {
                    }
                }).setOnEmojiPopupShownListener(new OnEmojiPopupShownListener() {
                    @Override
                    public void onEmojiPopupShown() {
                        emojiButton.setBackground(AppCompatResources.getDrawable(
                                getContext(), R.drawable.outline_keyboard_black_48));
                        
                    }
                }).setOnSoftKeyboardOpenListener(new OnSoftKeyboardOpenListener() {
                    @Override
                    public void onKeyboardOpen(final int keyBoardHeight) {
                    }
                }).setOnEmojiPopupDismissListener(new OnEmojiPopupDismissListener() {
                    @Override
                    public void onEmojiPopupDismiss() {
                        emojiButton.setBackground(AppCompatResources.getDrawable(
                                getContext(), R.drawable.outline_emoji_emotions_black_48));
                        
                    }
                }).setOnSoftKeyboardCloseListener(new OnSoftKeyboardCloseListener() {
                    @Override
                    public void onKeyboardClose() {
                        emojiPopup.dismiss();
                    }
                }).build(emojiconEditText);
    }
```

**Comment by hvar90** [comment]
maybe it is because i am using java code, how could i use the new versions with my java code?

**Comment by vanniktech** [comment]
First upgrade to 0.10.0, Builder got deprecated and removed in 0.11.0. As for the parameter it's been removed from `OnEmojiClickListener`: https://github.com/vanniktech/Emoji/blob/master/emoji/src/main/kotlin/com/vanniktech/emoji/listeners/OnEmojiClickListener.kt

Instead of Builder you can directly call the EmojiPopup constructor

**Comment by hvar90** [comment]
> EmojiPopup

a question 
EmojiPopup has notnull parameters, what happens when i do not need to put all parameters like EmojiTheming?
and the parameters have an ordering 
with the builder we could put optional values

thanks for your answer
