### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#785]
i got errors with the new library

Version of the library:
emoji-ios:0.10.0
Affected devices:
samsung
Affected versions:
android 11

non-static method install(EmojiProvider) cannot be referenced from a static context

you have on the tutorial 
`EmojiManager.install(IosEmojiProvider());` 
but it does not work anymore because install method is not static anymore

cannot find symbol method fromRootView(NestedScrollViews)
` emojiPopup = EmojiPopup.Builder.fromRootView(ns)`
fromRootView does not exist anymore :(

<anonymous com.talkfi.profile.EditProfileActivity$18> is not abstract and does not override abstract method onEmojiBackspaceClick() in OnEmojiBackspaceClickListener
method does not override or implement a method from a supertype
cannot find symbol method fromRootView(View)
```
emojiPopup = EmojiPopup.Builder.fromRootView(rootView)
                .setPageTransformer(new PageTransformer())
                .setOnEmojiBackspaceClickListener(new OnEmojiBackspaceClickListener() {
                    @Override
                    public void onEmojiBackspaceClick(View v) {
                    }
                })
```

non-static method emojisCount(CharSequence) cannot be referenced from a static context
non-static method isOnlyEmojis(CharSequence) cannot be referenced from a static context
```
if (EmojiUtils.emojisCount(message) < 3 && EmojiUtils.isOnlyEmojis(message)) {
            int pixels = (int) (33 * scale + 0.5f);
            txtMsg.setEmojiSize(pixels);
        }
```
how could use this methods? because EmojiUtils has private access

that is all, thanks for your help

**Comment by vanniktech** [comment]
I'm not here to explain to you how to call Kotlin code from Java. There are plenty of tutorial online. So for instance you might need: `EmojiManager.INSTANCE.install`
