### ISSUE TITLE
Error: IllegalStateException

### ISSUE THREAD

**Issue by lendra85** [vanniktech/Emoji#85]
I found the error like this:
java.lang.IllegalStateException: Please install an EmojiProvider through the install method first.
Could you help me? previously it was worked.

**Comment by acemimhnds** [comment]
2 days ago it was working but now I am getting this error. 
How can i solve it ?

**Comment by rubengees** [comment]
@lendra85 @acemimhnds 

There was a large update some days ago. You can either use the stable `0.3` version or do some adjustments for the latest `SNAPSHOT`.

You can now choose between Ios Emojis and EmojiOne. The new dependency is either

```groovy
compile 'com.vanniktech:emoji-ios:0.4.0'
```
or
```groovy
compile 'com.vanniktech:emoji-one:0.4.0'
```

After that, you have to install the `Provider` of the chosen variant. A good place is in an `Application` subclass. This would look like this:

```java
EmojiManager.install(new IosEmojiProvider())
```
or
```java
EmojiManager.install(new EmojiOneProvider())
```

After that it will work like before, but with the latest emojis and better quality ones. :grinning:

**Comment by zh-hl** [comment]
Is this a permanent fix ? I hope the Readme.md page got updated with this information soon.

**Comment by rubengees** [comment]
@zh-hl 
There is always a risk when using a `SNAPSHOT` version.
Yes, there is already a PR for documentation of these changes, have a look at the `readme` branch.

**Comment by vanniktech** [comment]
@zh-hl yes README gets an update with #83

I'll prepare 0.4.0 in the next days. Sorry for the inconvenience.

And yes using SNAPSHOT versions always has a risk.
