### ISSUE TITLE
Emoji SHOULD not blur

### ISSUE THREAD

**Issue by buiduclam09** [vanniktech/Emoji#862]
- Version of the library: 0.8
- Affected devices: android Samsung FE, version 12
- Affected versions:
![image](https://user-images.githubusercontent.com/101542618/174708257-00e93bec-7dc2-48de-8f92-7c9079756f5d.png)

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
What's the problem here?

**Comment by buiduclam09** [comment]
When load with Imageview size: 300*300px. Icon will blur,

**Comment by vanniktech** [comment]
Yeah emojis aren't meant to be displayed in such a big size. There's really nothing we can do as we use images and not svgs.
