### ISSUE TITLE
failed to resolve com.vanniktech:emoji-ios:0.4.0

### ISSUE THREAD

**Issue by hvar90** [vanniktech/Emoji#87]
i am triying to put the new version and i get 
failed to resolve com.vanniktech:emoji-ios:0.4.0

i am following the instructions of here 
https://github.com/vanniktech/Emoji/tree/readme

**Comment by rubengees** [comment]
This version is not released yet.
Please try `com.vanniktech:emoji-ios:0.4.0-SNAPSHOT` instead.
I suggest to change it to the variant without `SNAPSHOT` though once it comes out, as `SNAPSHOTS` can break your build without further notice.

**Comment by hvar90** [comment]
ok, so , i gonna wait until the new version be released then i will use  com.vanniktech:emoji-ios:0.4.0

**Comment by vanniktech** [comment]
I'll try to release 0.4.0 in the next 1-3 days since I'm back now.

**Comment by vanniktech** [comment]
@hvar90 @rubengees It's released now. Thanks for your patience.

**Comment by hvar90** [comment]
@vanniktech  good job 
by the way , i have a startup, maybe you and me can work together in the future
