### ISSUE TITLE
Cannot resolve symbol 'Builder'

### ISSUE THREAD

**Issue by SujithManjavana** [vanniktech/Emoji#879]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: com.vanniktech:emoji-google:0.15.0"
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

I'm getting this error in android studio from my java project, Cannot resolve symbol 'Builder' with this code ` emojiPopup = EmojiPopup.Builder.fromRootView(findViewById(R.id.chat_root_view)).build(msgBox);`, But if I use `emojiPopup = new EmojiPopup(findViewById(R.id.chat_root_view), msgBox);` everything works fine.

**Comment by vanniktech** [comment]
Builder has been removed. Use the EmojiPopup constructor!
