### ISSUE TITLE
Cannot resolve method 'setOnEmojiPopupShownListener' in 'EmojiPopup'

### ISSUE THREAD

**Issue by SujithManjavana** [vanniktech/Emoji#880]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: "com.vanniktech:emoji-facebook:0.15.0"
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reproduction steps are appreciated.

----------------------------------------------------------------------
Why is android studio showing this error? `Cannot resolve method 'setOnEmojiPopupShownListener' in 'EmojiPopup'`
This is the java code I'm running:
`emojiPopup.setOnEmojiPopupShownListener((OnEmojiPopupShownListener) () -> emojiBtn.setImageResource(R.drawable.ic_keyboard_24dp));`

**Comment by vanniktech** [comment]
Please have a look at the kotlin constructor those methods are all gone as stated in the release notes

**Comment by SujithManjavana** [comment]
Please update your docs to match the latest version. Thank you for this
wonderful library 😊.

**Comment by vanniktech** [comment]
As far as I know, README and sample are both up to date.
