### ISSUE TITLE
Category icons aren't visible (translucent or pure white?)

### ISSUE THREAD

**Issue by tinder-johnbuhanan** [vanniktech/Emoji#885]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.15.0
- Affected devices: Pixel 5a
- Affected versions: 0.15.0

Screenshot(s) showing the issue and reprodution steps are appreciated.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/102559887/187531231-1f2d5610-eab9-4bf1-a252-bd4ce05c74c4.png">
----------------------------------------------------------------------

I launch it from one app and they show up fine.

But if I launch it from our production app I can't see the buttons.

What could cause this?  Some kind of styling?  How do I fix?

**Comment by santi-petersen** [comment]
Probably some issue with your app theme. Check the "colorPrimary" in your AppTheme style. This is the color used to display unselected categories.

**Comment by JohnBuhanan** [comment]
@santi-petersen 
Is there a workaround? I can't change color primary :(

**Comment by santi-petersen** [comment]
@JohnBuhanan 
I guess you can pass a different EmojiTheming() to the EmojiPopup constructor 

val EmojiPopup(
...
theming = EmojiTheming(primaryColor = Color.DKGRAY)
)

**Comment by JohnBuhanan** [comment]
Badass!  I'll try it :)

**Comment by vanniktech** [comment]
Yeah please use [`EmojiTheming`](https://github.com/vanniktech/Emoji/blob/ae46e82faaa8a1587005efa33c0561a29b6d159a/emoji/src/androidMain/kotlin/com/vanniktech/emoji/EmojiTheming.kt) to overwrite theming.
