### ISSUE TITLE
EmojiTextView not rendering emojis properly

### ISSUE THREAD

**Issue by SujithManjavana** [vanniktech/Emoji#886]
Some emojis are not rendering correctly on EmojiTextView. As you can see in the attached screenshot, those emojis are rendered by the android system. This problem only happens with EmojiTextView, in EmojiEditText it is rendered properly.
My code:
`
 <com.vanniktech.emoji.EmojiTextView
            android:id="@+id/sentTxt"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="@dimen/chat_text_margin_start"
            android:layout_marginTop="@dimen/chat_text_margin"
            android:layout_marginEnd="@dimen/chat_text_margin"
            android:layout_marginBottom="@dimen/chat_text_margin"
            android:autoLink="all"
            android:longClickable="false"
            android:maxWidth="@dimen/chat_item_max_width"
            android:textColor="?chatTxtColor"
            android:textColorLink="?attr/chatLinkColorSent"
            android:textIsSelectable="false"
            android:textSize="@dimen/chat_text_size"
            app:emojiSize="@dimen/chat_emoji_size"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/replyUI"
            tools:text="Hi" />
`

- Version of the library: com.vanniktech:emoji-ios:0.15.0
- Affected devices: android 11, not tested on other versions

Screenshot(s) showing the issue and reproduction steps are appreciated.

----------------------------------------------------------------------
![chat](https://user-images.githubusercontent.com/51516724/188262233-2e2c49c1-3a99-4faa-b3f6-4f4fce830030.jpeg)

**Comment by vanniktech** [comment]
This is the same as #788
