### ISSUE TITLE
Can we support fluent emoji by microsoft?

### ISSUE THREAD

**Issue by tarcrud** [vanniktech/Emoji#894]
This would be cool.

**Comment by vanniktech** [comment]
Deferring to my importing hero: @rubengees

**Comment by rubengees** [comment]
As we get our Emojis from an external package, this would depend on https://github.com/iamcal/emoji-data/issues/211.

**Comment by vanniktech** [comment]
Oh wow they look actually good!

**Comment by vanniktech** [comment]
Closing for now. Let's subscribe to their issue and once our source supports them, we can make a package out of them.
