### ISSUE TITLE
I cant add your library in my project. I have error Failed to resolve: com.vanniktech:emoji-one:0.4.0.  Old version com.vanniktech:emoji:0.4.0-SNAPSHOT worked fine

### ISSUE THREAD

**Issue by islavstan** [vanniktech/Emoji#90]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.4.0
- Affected devices: nexus 4
- Affected versions: 19

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
@islavstan could you check again? 0.4.0 should be uploaded

**Comment by vanniktech** [comment]
It's released. Again sorry for the inconvenience.
