### ISSUE TITLE
 why can't extend EmojiPopup , Why give up the power of Java

### ISSUE THREAD

**Issue by SheTieJun** [vanniktech/Emoji#920]
- Version of the library:  v0.15.0
- Affected devices: all
- Affected versions: all

some problems cannot be solved, if it can be extend, it should be solved very well. last  use reflection solved.

**Comment by vanniktech** [comment]
Delegation is better than inheritance. Plus I want to limit the API. Feel free to use reflection though, it might break though.

**Comment by SheTieJun** [comment]
Delegation and inheritance do not conflict ,  Like Activity ，bottomSheetDailog. 
Limit EmojiPopup 's API ,~ en  I think it is unnecessary behavior.
