### ISSUE TITLE
Unable to build project, gradle error

### ISSUE THREAD

**Issue by kunal-das-koo-app** [vanniktech/Emoji#928]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library:
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.
![image](https://user-images.githubusercontent.com/121296666/210501808-74100fb4-70b7-4f57-9079-d1eae2bf12d9.png)

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
Please report this to the Android Studio Team. Also maybe you need to update Android Studio
