### ISSUE TITLE
Emoji category icons are barely visible in Day mode theme 

### ISSUE THREAD

**Issue by onirban27** [vanniktech/Emoji#939]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.15.0
- Affected devices: xiaomi
- Affected versions: Android 13, 12
![Screenshot_20230126-172128](https://user-images.githubusercontent.com/42543639/214824383-5e38ff6c-b9dc-4cbe-9912-381436164287.png)

In dark mode its ok but for day theme it's all white.
This is working in 0.7.0 version 

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
This does work in the sample app. Please check it.
