### ISSUE TITLE
How to scroll the recyclerview to the bottom when keyboard visibility changes

### ISSUE THREAD

**Issue by SujithManjavana** [vanniktech/Emoji#943]
Earlier I used the following code to scroll the chat to the bottom when keyboard visibility changes,
`
View rootView = findViewById(R.id.chat_root_view).getRootView();
        ViewCompat.setOnApplyWindowInsetsListener(rootView, (v, insets) -> {
            scrollToBottom();
            return insets;
        });
`
But after adding EmojiKeyboard to my project it is not working. How can I fix it?

**Comment by vanniktech** [comment]
Please consult with the sample app and otherwise ask on Stackoverflow.
