### ISSUE TITLE
emoji_text_view xml doesnt show

### ISSUE THREAD

**Issue by atynnn** [vanniktech/Emoji#966]
hi. may i ask, why when i try using the <com.vanniktech.emoji.EmojiTextView or even the other layout fx in emoji_text_view.xml, i cant see the gui ? i still can run the program but it can only display one text of reaction instead of multiple ones.

this is the code n layout:
![image](https://user-images.githubusercontent.com/107984658/229278901-684d493d-a7de-4cde-8d17-b92f7b691b1d.png)

while this is the output (i can only send comment once):
![image](https://user-images.githubusercontent.com/107984658/229278970-b15239cf-bf97-4020-9574-cb65b84b160f.png)

one error shown?:
![image](https://user-images.githubusercontent.com/107984658/229279080-e5a7767e-5582-4701-8412-de1b4f442266.png)

 i have already done everything exactly the same as other videos and codes. i also did a new project, following the same gui as the youtube videos, but my xml still doesnt show the gui

**Comment by vanniktech** [comment]
Bug in AS. Report there please
