### ISSUE TITLE
iOS 16.4 emojis

### ISSUE THREAD

**Issue by tiennv157** [vanniktech/Emoji#988]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.16.0
- Affected devices:
- Affected versions:

Screenshot(s) showing the issue and reprodution steps are appreciated.

<img width="1202" alt="Screenshot 2023-06-27 at 15 14 23" src="https://github.com/vanniktech/Emoji/assets/49298106/7bafb111-db2e-4304-86e3-c68b3475fa1b">

![2023-06-27 15 17 44](https://github.com/vanniktech/Emoji/assets/49298106/db55d20c-0a81-4357-b438-111b904fcba8)

----------------------------------------------------------------------

**Comment by vanniktech** [comment]
please try out the snapshot version which will be published soon :)

**Comment by tiennv157** [comment]
Hi @vanniktech
Thanks for your hard work. But I got an issue in 0.17.0 version

EmojiEditText is OK
![2023-06-28 11 39 56](https://github.com/vanniktech/Emoji/assets/49298106/49f9f5ad-f809-4edf-87ea-fc362f1edf0e)

But It's wrong in EmojiTextView
![2023-06-28 11 40 00](https://github.com/vanniktech/Emoji/assets/49298106/a0c7d55e-ac3a-4395-89a3-581b41ad70ba)


Device Info: Red 9C - Android 10
